<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ContentTenangSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $quranVerses = [
            ['surah' => 13, 'ayat_number' => 28, 'arabic_text' => 'الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُمْ بِذِكْرِ اللَّهِ ۗ أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ', 'translation' => '(Yaitu) orang-orang yang beriman dan hati mereka menjadi tenteram dengan mengingat Allah. Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.', 'tags' => 'tenang, tuma\'ninah, zikir, ketenangan hati'],
            ['surah' => 48, 'ayat_number' => 4, 'arabic_text' => 'هُوَ الَّذِي أَنْزَلَ السَّكِينَةَ فِي قُلُوبِ الْمُؤْمِنِينَ لِيَزْدَادُوا إِيمَانًا مَعَ إِيمَانِهِمْ', 'translation' => 'Dialah yang telah menurunkan ketenangan ke dalam hati orang-orang mukmin untuk menambah iman atas iman mereka (yang telah ada).', 'tags' => 'tenang, sakinah, iman, ketenangan jiwa'],
            ['surah' => 48, 'ayat_number' => 18, 'arabic_text' => 'لَقَدْ رَضِيَ اللَّهُ عَنِ الْمُؤْمِنِينَ إِذْ يُبَايِعُونَكَ تَحْتَ الشَّجَرَةِ فَعَلِمَ مَا فِي قُلُوبِهِمْ فَأَنْزَلَ السَّكِينَةَ عَلَيْهِمْ', 'translation' => 'Sungguh, Allah telah ridha terhadap orang-orang mukmin ketika mereka berjanji setia kepadamu di bawah pohon, Dia mengetahui apa yang ada dalam hati mereka lalu Dia menurunkan ketenangan atas mereka...', 'tags' => 'tenang, sakinah, ridha Allah'],
            ['surah' => 48, 'ayat_number' => 26, 'arabic_text' => 'فَأَنْزَلَ اللَّهُ سَكِينَتَهُ عَلَىٰ رَسُولِهِ وَعَلَى الْمُؤْمِنِينَ وَأَلْزَمَهُمْ كَلِمَةَ التَّقْوَىٰ', 'translation' => '...Maka Allah menurunkan ketenangan kepada Rasul-Nya dan kepada orang-orang mukmin, dan menetapkan bagi mereka kalimat takwa...', 'tags' => 'tenang, sakinah, pertolongan Allah'],
            ['surah' => 9, 'ayat_number' => 26, 'arabic_text' => 'ثُمَّ أَنْزَلَ اللَّهُ سَكِينَتَهُ عَلَىٰ رَسُولِهِ وَعَلَى الْمُؤْمِنِينَ وَأَنْزَلَ جُنُودًا لَمْ تَرَوْهَا', 'translation' => 'Kemudian Allah menurunkan ketenangan kepada Rasul-Nya dan kepada orang-orang yang beriman, dan Dia menurunkan pasukan yang tidak kamu lihat...', 'tags' => 'tenang, sakinah, pertolongan'],
            ['surah' => 9, 'ayat_number' => 40, 'arabic_text' => 'إِذْ يَقُولُ لِصَاحِبِهِ لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا ۖ فَأَنْزَلَ اللَّهُ سَكِينَتَهُ عَلَيْهِ', 'translation' => '...ketika dia berkata kepada sahabatnya, \'Janganlah engkau berduka cita, sesungguhnya Allah bersama kita.\' Maka Allah menurunkan ketenangan-Nya kepadanya...', 'tags' => 'tenang, sakinah, pendampingan Allah'],
            ['surah' => 2, 'ayat_number' => 248, 'arabic_text' => 'إِنَّ آيَةَ مُلْكِهِ أَنْ يَأْتِيَكُمُ التَّابُوتُ فِيهِ سَكِينَةٌ مِنْ رَبِّكُمْ', 'translation' => 'Dan nabi mereka berkata kepada mereka, \'Sesungguhnya tanda kerajaannya ialah datangnya Tabut kepadamu, yang di dalamnya terdapat ketenangan dari Tuhanmu...\'', 'tags' => 'tenang, sakinah, tanda kekuasaan'],
            ['surah' => 89, 'ayat_number' => 27, 'arabic_text' => 'يَا أَيَّتُهَا النَّفْسُ الْمُطْمَئِنَّةُ', 'translation' => 'Wahai jiwa yang tenang!', 'tags' => 'tenang, jiwa tenang, mutma\'innah'],
            ['surah' => 89, 'ayat_number' => 28, 'arabic_text' => 'ارْجِعِي إِلَىٰ رَبِّكِ رَاضِيَةً مَرْضِيَّةً', 'translation' => 'Kembalilah kepada Tuhanmu dengan hati yang ridha dan diridhai-Nya.', 'tags' => 'tenang, kedamaian, ridha Allah'],
            ['surah' => 89, 'ayat_number' => 29, 'arabic_text' => 'فَادْخُلِي فِي عِبَادِي', 'translation' => 'Maka masuklah ke dalam golongan hamba-hamba-Ku,', 'tags' => 'tenang, hamba Allah, kedamaian'],
            ['surah' => 89, 'ayat_number' => 30, 'arabic_text' => 'وَادْخُلِي جَنَّتِي', 'translation' => 'dan masuklah ke dalam surga-Ku.', 'tags' => 'tenang, surga, puncak ketenangan'],
            ['surah' => 94, 'ayat_number' => 1, 'arabic_text' => 'أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ', 'translation' => 'Bukankah Kami telah melapangkan dadamu (Muhammad)?', 'tags' => 'tenang, lapang dada, kelegaan'],
            ['surah' => 30, 'ayat_number' => 21, 'arabic_text' => 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُمْ مِنْ أَنْفُسِكُمْ أَزْوَاجًا لِتَسْكُنُوا إِلَيْهَا', 'translation' => 'Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu merasa tenteram/tenang kepadanya...', 'tags' => 'tenang, ketenteraman, pasangan'],
            ['surah' => 2, 'ayat_number' => 186, 'arabic_text' => 'وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ', 'translation' => 'Dan apabila hamba-hamba-Ku bertanya kepadamu tentang Aku, maka bahwasanya Aku adalah dekat. Aku mengabulkan permohonan orang yang berdoa apabila ia berdoa kepada-Ku...', 'tags' => 'tenang, kedekatan Allah, doa'],
            ['surah' => 10, 'ayat_number' => 62, 'arabic_text' => 'أَلَا إِنَّ أَوْلِيَاءَ اللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ', 'translation' => 'Ingatlah, sesungguhnya wali-wali Allah itu tidak ada kekhawatiran terhadap mereka dan tidak (pula) mereka bersedih hati.', 'tags' => 'tenang, bebas cemas, wali Allah'],
            ['surah' => 16, 'ayat_number' => 106, 'arabic_text' => 'إِلَّا مَنْ أُكْرِهَ وَقَلْبُهُ مُطْمَئِنٌّ بِالْإِيمَانِ', 'translation' => '...kecuali orang yang dipaksa melakukan kufr sedangkan hatinya tetap tenang dalam beriman...', 'tags' => 'tenang, keteguhan iman, tuma\'ninah'],
            ['surah' => 8, 'ayat_number' => 10, 'arabic_text' => 'وَمَا جَعَلَهُ اللَّهُ إِلَّا بُشْرَىٰ وَلِتَطْمَئِنَّ بِهِ قُلُوبُكُمْ', 'translation' => 'Dan tidaklah Allah menjadikannya melainkan sebagai kabar gembira dan agar hatimu menjadi tenteram dengannya...', 'tags' => 'tenang, kabar gembira, tenteram'],
            ['surah' => 3, 'ayat_number' => 126, 'arabic_text' => 'وَمَا جَعَلَهُ اللَّهُ إِلَّا بُشْرَىٰ لَكُمْ وَلِتَطْمَئِنَّ قُلُوبُكُمْ بِهِ', 'translation' => 'Dan tidaklah Allah menjadikannya melainkan sebagai kabar gembira bagi kamu, dan agar hatimu tenteram karenanya...', 'tags' => 'tenang, ketenteraman hati, janji Allah'],
            ['surah' => 8, 'ayat_number' => 11, 'arabic_text' => 'إِذْ يُغَشِّيكُمُ النُّعَاسَ أَمَنَةً مِنْهُ... وَلِيَرْبِطَ عَلَىٰ قُلُوبِكُمْ وَيُثَبِّتَ بِهِ الْأَقْدَامَ', 'translation' => '(Ingatlah) ketika Allah membuat kamu mengantuk untuk memberi ketenangan dari-Nya... dan untuk meneguhkan hatimu serta memperkuat pendirianmu.', 'tags' => 'tenang, rasa aman, peneguh hati'],
            ['surah' => 20, 'ayat_number' => 46, 'arabic_text' => 'قَالَ لَا تَخَافَا ۖ إِنَّنِي مَعَكُمَا أَسْمَعُ وَأَرَىٰ', 'translation' => 'Dia (Allah) berfirman: \'Janganlah kamu berdua takut, sesungguhnya Aku bersama kamu berdua, Aku mendengar dan melihat.\'', 'tags' => 'tenang, kedamaian, perlindungan Allah'],
            ['surah' => 28, 'ayat_number' => 10, 'arabic_text' => 'لَوْلَا أَنْ رَبَطْنَا عَلَىٰ قَلْبِهَا لِتَكُونَ مِنَ الْمُؤْمِنِينَ', 'translation' => '...seandainya tidak Kami teguhkan hatinya (ibu Musa), agar dia termasuk orang-orang yang beriman (lagi tenang).', 'tags' => 'tenang, keteguhan batin, rahmat'],
            ['surah' => 41, 'ayat_number' => 30, 'arabic_text' => 'إِنَّ الَّذِينَ قَالُوا رَبُّنَا اللَّهُ ثُمَّ اسْتَقَامُوا تَتَنَزَّلُ عَلَيْهِمُ الْمَلَائِكَةُ أَلَّا تَخَافُوا وَلَا تَحْزَنُوا', 'translation' => 'Sesungguhnya orang-orang yang berkata \'Tuhan kami ialah Allah\' kemudian mereka meneguhkan pendirian mereka, maka malaikat akan turun kepada mereka (dengan mengatakan): \'Janganlah kamu takut dan janganlah merasa sedih...\'', 'tags' => 'tenang, kabar malaikat, istiqamah'],
            ['surah' => 6, 'ayat_number' => 82, 'arabic_text' => 'الَّذِينَ آمَنُوا وَلَمْ يَلْبِسُوا إِيمَانَهُمْ بِظُلْمٍ أُولَٰئِكَ لَهُمُ الْأَمْنُ وَهُمْ مُهْتَدُونَ', 'translation' => 'Orang-orang yang beriman dan tidak mencampuradukkan iman mereka dengan kezaliman (syirik), mereka itulah yang mendapat rasa aman (ketenangan) dan mereka itulah orang-orang yang mendapat petunjuk.', 'tags' => 'tenang, rasa aman, tauhid'],
            ['surah' => 106, 'ayat_number' => 4, 'arabic_text' => 'الَّذِي أَطْعَمَهُمْ مِنْ جُوعٍ وَآمَنَهُمْ مِنْ خَوْفٍ', 'translation' => 'Yang telah memberi makanan kepada mereka untuk menghilangkan lapar dan mengamankan mereka dari rasa takut.', 'tags' => 'tenang, rasa aman, nikmat Allah'],
            ['surah' => 16, 'ayat_number' => 112, 'arabic_text' => 'وَضَرَبَ اللَّهُ مَثَلًا قَرْيَةً كَانَتْ آمِنَةً مُطْمَئِنَّةً يَأْتِيهَا رِزْقُهَا رَغَدًا مِنْ كُلِّ مَكَانٍ', 'translation' => 'Dan Allah telah membuat suatu perumpamaan (dengan) sebuah negeri yang dahulunya aman lagi tenteram, rezekinya datang kepadanya melimpah ruah dari segenap tempat...', 'tags' => 'tenang, negeri tenteram, rezeki'],
            ['surah' => 28, 'ayat_number' => 73, 'arabic_text' => 'وَمِنْ رَحْمَتِهِ جَعَلَ لَكُمُ اللَّيْلَ وَالنَّهَارَ لِتَسْكُنُوا فِيهِ', 'translation' => 'Dan adalah karena rahmat-Nya, Dia jadikan untukmu malam dan siang, agar kamu beristirahat/tenang pada malam hari...', 'tags' => 'tenang, istirahat, rahmat Allah'],
            ['surah' => 10, 'ayat_number' => 67, 'arabic_text' => 'هُوَ الَّذِي جَعَلَ لَكُمُ اللَّيْلَ لِتَسْكُنُوا فِيهِ وَالنَّهَارَ مُبْصِرًا', 'translation' => 'Dialah yang menjadikan malam bagimu supaya kamu beristirahat (tenang) padanya dan menjadikan siang terang benderang...', 'tags' => 'tenang, kedamaian malam, hikmah'],
            ['surah' => 40, 'ayat_number' => 61, 'arabic_text' => 'اللَّهُ الَّذِي جَعَلَ لَكُمُ اللَّيْلَ لِتَسْكُنُوا فِيهِ وَالنَّهَارَ مُبْصِرًا', 'translation' => 'Allah-lah yang menjadikan malam untukmu supaya kamu beristirahat (tenang) padanya dan menjadikan siang terang benderang...', 'tags' => 'tenang, waktu tenang, kuasa Allah'],
            ['surah' => 6, 'ayat_number' => 96, 'arabic_text' => 'فَالِقُ الْإِصْبَاحِ وَجَعَلَ اللَّيْلَ سَكَنًا', 'translation' => 'Dia menyingsingkan pagi dan menjadikan malam untuk beristirahat/ketenangan...', 'tags' => 'tenang, ketenangan malam, tanda alam'],
            ['surah' => 9, 'ayat_number' => 103, 'arabic_text' => 'وَصَلِّ عَلَيْهِمْ ۖ إِنَّ صَلَاتَكَ سَكَنٌ لَهُمْ', 'translation' => '...Dan mendoakanlah untuk mereka. Sesungguhnya doa kamu itu (menjadi) ketenangan jiwa bagi mereka...', 'tags' => 'tenang, doa rasul, ketenangan jiwa'],
            ['surah' => 2, 'ayat_number' => 260, 'arabic_text' => 'قَالَ أَوَلَمْ تُؤْمِنْ ۖ قَالَ بَلَىٰ وَلَٰكِنْ لِيَطْمَئِنَّ قَلْبِي', 'translation' => 'Allah berfirman: \'Belum yakinkah engkau?\' Ibrahim menjawab: \'Aku telah meyakininya, akan tetapi agar hatiku menjadi tenang (mantap).\'', 'tags' => 'tenang, ketenangan keyakinan, Nabi Ibrahim'],
            ['surah' => 3, 'ayat_number' => 173, 'arabic_text' => 'الَّذِينَ قَالَ لَهُمُ النَّاسُ إِنَّ النَّاسَ قَدْ جَمَعُوا لَكُمْ فَاخْشَوْهُمْ فَزَادَهُمْ إِيمَانًا وَقَالُوا حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ', 'translation' => '...dan mereka menjawab: \'Cukuplah Allah menjadi Penolong kami dan Dia adalah sebaik-baik Pelindung.\'', 'tags' => 'tenang, tawakal, penentram batin'],
            ['surah' => 26, 'ayat_number' => 62, 'arabic_text' => 'قَالَ كَلَّا ۖ إِنَّ مَعِيَ رَبِّي سَيَهْدِينِ', 'translation' => 'Dia (Musa) menjawab: \'Sekali-kali tidak! Sesungguhnya Tuhanku bersamaku, Dia akan memberi petunjuk kepadaku.\'', 'tags' => 'tenang, keyakinan, pertolongan'],
            ['surah' => 93, 'ayat_number' => 3, 'arabic_text' => 'مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ', 'translation' => 'Tuhanmu tidak meninggalkan engkau (Muhammad) dan tidak (pula) membencimu.', 'tags' => 'tenang, penghibur, kasih sayang'],
            ['surah' => 94, 'ayat_number' => 5, 'arabic_text' => 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا', 'translation' => 'Maka sesungguhnya bersama kesulitan ada kemudahan.', 'tags' => 'tenang, kemudahan, harapan'],
        ];

        $hadiths = [
            ['arabic_text' => 'مَا اجْتَمَعَ قَوْمٌ فِي بَيْتٍ مِنْ بُيُوتِ اللَّهِ يَتْلُونَ كِتَابَ اللَّهِ وَيَتَدَارَسُونَهُ بَيْنَهُمْ إِلاَّ نَزَلَتْ عَلَيْهِمُ السَّكِينَةُ وَغَشِيَتْهُمُ الرَّحْمَةُ', 'translation' => 'Tidaklah suatu kaum berkumpul di salah satu rumah Allah membaca Kitabullah dan saling mempelajarinya di antara mereka, melainkan akan turun kepada mereka ketenangan (sakinah) dan diliputi rahmat...', 'book' => 'Muslim', 'number' => '2699', 'source' => 'HR. Muslim no. 2699'],
            ['arabic_text' => 'اقْرَأْ فُلاَنُ فَإِنَّهَا السَّكِينَةُ تَنَزَّلَتْ لِلْقُرْآنِ', 'translation' => 'Bacalah terus wahai fulan, sesungguhnya itu adalah ketenangan (sakinah) yang turun karena (bacaan) Al-Qur\'an.', 'book' => 'Bukhari, Muslim', 'number' => '5011, 795', 'source' => 'HR. Bukhari no. 5011 & Muslim no. 795'],
            ['arabic_text' => 'دَعْ مَا يَرِيبُكَ إِلَى مَا لاَ يَرِيبُكَ فَإِنَّ الصِّدْقَ طُمَأْنِينَةٌ وَإِنَّ الْكَذِبَ رِيبَةٌ', 'translation' => 'Tinggalkanlah apa yang meragukanmu menuju apa yang tidak meragukanmu. Sesungguhnya kejujuran itu membawa ketenangan (tuma\'ninah) dan kedustaan itu membawa keraguan.', 'book' => 'Tirmidzi', 'number' => '2518', 'source' => 'HR. Tirmidzi no. 2518'],
            ['arabic_text' => 'الْبِرُّ مَا اطْمَأَنَّتْ إِلَيْهِ النَّفْسُ وَاطْمَأَنَّ إِلَيْهِ الْقَلْبُ', 'translation' => 'Kebaikan itu adalah apa yang membuat jiwa merasa tenteram dan hati merasa tenang kepadanya...', 'book' => 'Ahmad, Ad-Darimi', 'number' => '17742', 'source' => 'HR. Ahmad no. 17742 & Ad-Darimi'],
            ['arabic_text' => 'إِذَا أُقِيمَتِ الصَّلاَةُ فَلاَ تَأْتُوهَا وَأَنْتُمْ تَسْعَوْنَ وَأْتُوهَا تَمْشُونَ وَعَلَيْكُمُ السَّكِينَةُ', 'translation' => 'Apabila salat telah diiqamahkan, janganlah kalian mendatanginya dengan berlari, tetapi datangilah dengan berjalan biasa dan hendaklah kalian bersikap tenang (sakinah)...', 'book' => 'Bukhari, Muslim', 'number' => '908, 602', 'source' => 'HR. Bukhari no. 908 & Muslim no. 602'],
            ['arabic_text' => 'أَرِحْنَا بِهَا يَا بِلاَلُ', 'translation' => 'Istirahatkanlah kami (buatlah kami tenang/tenteram) dengan salat, wahai Bilal!', 'book' => 'Abu Dawud', 'number' => '4985', 'source' => 'HR. Abu Dawud no. 4985'],
            ['arabic_text' => 'وَجُعِلَتْ قُرَّةُ عَيْنِي فِي الصَّلاَةِ', 'translation' => '...Dan dijadikan puncak ketenangan/kesenanganku berada di dalam salat.', 'book' => 'An-Nasa\'i', 'number' => '3940', 'source' => 'HR. An-Nasa\'i no. 3940'],
            ['arabic_text' => 'اللَّهُمَّ أَنْتَ السَّلاَمُ وَمِنْكَ السَّلاَمُ تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَالإِكْرَامِ', 'translation' => 'Ya Allah, Engkau adalah Maha Sejahtera (sumber kedamaian/ketenangan) dan dari-Mulah kesejahteraan...', 'book' => 'Muslim', 'number' => '591', 'source' => 'HR. Muslim no. 591'],
            ['arabic_text' => 'اللَّهُمَّ إِنِّي أَسْأَلُكَ النَّفْسَ الْمُطْمَئِنَّةَ تُؤْمِنُ بِلِقَائِكَ وَتَرْضَى بِقَضَائِكَ وَتَقْنَعُ بِعَطَائِكَ', 'translation' => 'Ya Allah, aku memohon kepada-Mu jiwa yang tenang, yang beriman akan perjumpaan dengan-Mu, ridha atas ketetapan-Mu, dan merasa cukup dengan pemberian-Mu.', 'book' => 'Thabrani', 'number' => null, 'source' => 'HR. Thabrani (Al-Mu\'jam al-Kabir)'],
            ['arabic_text' => 'عَجَبًا لأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ... إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ وَإِنْ أَصَابَتْهُ ضَرَّاءُ صَبَرَ فَكَانَ خَيْرًا لَهُ', 'translation' => 'Sungguh menakjubkan urusan seorang mukmin, seluruh urusannya adalah baik... Jika mendapatkan kesenangan ia bersyukur dan jika ditimpa kesusahan ia bersabar, maka itu baik baginya.', 'book' => 'Muslim', 'number' => '2999', 'source' => 'HR. Muslim no. 2999'],
            ['arabic_text' => 'أَنَا عِنْدَ ظَنِّ عَبْدِي بِي وَأَنَا مَعَهُ إِذَا ذَكَرَنِي', 'translation' => 'Aku sesuai dengan persangkaan hamba-Ku kepada-Ku, dan Aku bersamanya apabila ia mengingat-Ku.', 'book' => 'Bukhari, Muslim', 'number' => '7405, 2675', 'source' => 'HR. Bukhari no. 7405 & Muslim no. 2675'],
            ['arabic_text' => 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ وَأَصْلِحْ لِي شَأْنِي كُلَّهُ', 'translation' => 'Ya Allah, rahmat-Mu yang aku harapkan, maka janganlah Engkau serahkan aku kepada diriku sendiri walau sekejap mata pun, dan perbaikilah seluruh urusanku.', 'book' => 'Abu Dawud', 'number' => '5090', 'source' => 'HR. Abu Dawud no. 5090'],
            ['arabic_text' => 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ', 'translation' => 'Ya Allah, aku berlindung kepada-Mu dari rasa cemas, sedih, lemah, dan malas.', 'book' => 'Bukhari', 'number' => '6369', 'source' => 'HR. Bukhari no. 6369'],
            ['arabic_text' => 'مَنْ أَصْبَحَ مِنْكُمْ آمِنًا فِي سِرْبِهِ مُعَافًى فِي جَسَدِهِ عِنْدَهُ قُوتُ يَوْمِهِ فَكَأَنَّمَا حِيزَتْ لَهُ الدُّنْيَا', 'translation' => 'Barangsiapa di antara kalian merasa aman di tempat tinggalnya, sehat badannya, dan memiliki makanan untuk harinya, maka seolah-olah dunia telah dikumpulkan untuknya.', 'book' => 'Tirmidzi', 'number' => '2346', 'source' => 'HR. Tirmidzi no. 2346'],
            ['arabic_text' => 'السَّكِينَةُ تُؤَدَّى فِي السَّلاَمِ', 'translation' => 'Ketenangan itu diwujudkan dalam kedamaian dan kelembutan.', 'book' => 'Bukhari, Muslim', 'number' => null, 'source' => 'HR. Bukhari (Fi al-Adab) & Muslim'],
        ];

        foreach ($quranVerses as $v) {
            $this->db->table('quran_verses')->insert(['surah' => $v['surah'], 'ayat_number' => $v['ayat_number'], 'arabic_text' => $v['arabic_text'], 'translation' => $v['translation'], 'source' => "Al-Qur'an", 'tags' => $v['tags'], 'status' => 'approved', 'created_at' => $now, 'updated_at' => $now]);
        }
        foreach ($hadiths as $h) {
            $this->db->table('hadiths')->insert(['arabic_text' => $h['arabic_text'], 'translation' => $h['translation'], 'book' => $h['book'], 'number' => $h['number'], 'source' => $h['source'], 'status' => 'approved', 'created_at' => $now, 'updated_at' => $now]);
        }

        echo 'Seeded ' . count($quranVerses) . ' quran verses and ' . count($hadiths) . ' hadiths (tenang).' . PHP_EOL;
    }
}
