<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ContentBersalahSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $quranVerses = [

            ['surah' => 39, 'ayat_number' => 53, 'arabic_text' => 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ', 'translation' => 'Katakanlah: \'Wahai hamba-hamba-Ku yang melampaui batas terhadap diri mereka sendiri, janganlah kamu berputus asa dari rahmat Allah. Sesungguhnya Allah mengampuni dosa-dosa semuanya. Sungguh, Dialah Yang Maha Pengampun lagi Maha Penyayang.\'', 'tags' => 'perasaan bersalah, ampunan dosa, rahmat Allah, taubat'],
            ['surah' => 3, 'ayat_number' => 135, 'arabic_text' => 'وَالَّذِينَ إِذَا فَعَلُوا فَاحِشَةً أَوْ ظَلَمُوا أَنْفُسَهُمْ ذَكَرُوا اللَّهَ فَاسْتَغْفَرُوا لِذُنُوبِهِمْ وَمَنْ يَغْفِرُ الذُّنُوبَ إِلَّا اللَّهُ', 'translation' => 'Dan (juga) orang-orang yang apabila mengerjakan perbuatan keji atau menzalimi diri sendiri, mereka segera ingat Allah, lalu memohon ampunan atas dosa-dosa mereka. Dan siapa lagi yang dapat mengampuni dosa selain Allah?', 'tags' => 'perasaan bersalah, kesadaran dosa, istighfar'],
            ['surah' => 4, 'ayat_number' => 110, 'arabic_text' => 'وَمَنْ يَعْمَلْ سُوءًا أَوْ يَظْلِمْ نَفْسَهُ ثُمَّ يَسْتَغْفِرِ اللَّهَ يَجِدِ اللَّهَ غَفُورًا رَحِيمًا', 'translation' => 'Dan barangsiapa mengerjakan kejahatan atau menzalimi dirinya sendiri, kemudian dia memohon ampunan kepada Allah, niscaya dia akan mendapati Allah Maha Pengampun lagi Maha Penyayang.', 'tags' => 'perasaan bersalah, istighfar, kasih sayang Allah'],
            ['surah' => 7, 'ayat_number' => 23, 'arabic_text' => 'قَالَا رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ', 'translation' => 'Keduanya berdoa: \'Ya Tuhan kami, kami telah menzalimi diri kami sendiri. Jika Engkau tidak mengampuni kami dan memberi rahmat kepada kami, niscaya kami termasuk orang-orang yang rugi.\'', 'tags' => 'perasaan bersalah, penyesalan, Nabi Adam, doa ampunan'],
            ['surah' => 28, 'ayat_number' => 16, 'arabic_text' => 'قَالَ رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي فَغَفَرَ لَهُ ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ', 'translation' => 'Dia (Musa) berdoa: \'Ya Tuhanku, sungguh aku telah menzalimi diriku sendiri, maka ampunilah aku.\' Maka Allah mengampuninya. Sungguh, Dialah Yang Maha Pengampun lagi Maha Penyayang.', 'tags' => 'perasaan bersalah, Nabi Musa, pengakuan dosa'],
            ['surah' => 21, 'ayat_number' => 87, 'arabic_text' => 'فَنَادَىٰ فِي الظُّلُمَاتِ أَنْ لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ', 'translation' => 'Maka dia (Yunus) berdoa dalam kegelapan yang berlapis-lapis: \'Tidak ada tuhan selain Engkau, Mahasuci Engkau. Sungguh, aku termasuk orang-orang yang zalim.\'', 'tags' => 'perasaan bersalah, penyesalan, Nabi Yunus, doa taubat'],
            ['surah' => 66, 'ayat_number' => 8, 'arabic_text' => 'يَا أَيُّهَا الَّذِينَ آمَنُوا تُوبُوا إِلَى اللَّهِ تَوْبَةً نَصُوحًا عَسَىٰ رَبُّكُمْ أَنْ يُكَفِّرَ عَنْكُمْ سَيِّئَاتِكُمْ', 'translation' => 'Wahai orang-orang yang beriman! Bertobatlah kepada Allah dengan tobat yang semurni-murninya (nasuha), mudah-mudahan Tuhanmu akan menghapus kesalahan-kesalahanmu...', 'tags' => 'perasaan bersalah, taubat nasuha, penghapus dosa'],
            ['surah' => 25, 'ayat_number' => 70, 'arabic_text' => 'إِلَّا مَنْ تَابَ وَآمَنَ وَعَمِلَ عَمَلًا صَالِحًا فَأُولَٰئِكَ يُبَدِّلُ اللَّهُ سَيِّئَاتِهِمْ حَسَنَاتٍ', 'translation' => 'Kecuali orang-orang yang bertobat, beriman, dan mengerjakan kebajikan; maka kejahatan mereka diganti Allah dengan kebaikan...', 'tags' => 'perasaan bersalah, penyesalan, transformasi dosa'],
            ['surah' => 2, 'ayat_number' => 222, 'arabic_text' => 'إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ', 'translation' => '...Sesungguhnya Allah menyukai orang-orang yang bertobat dan menyukai orang-orang yang menyucikan diri.', 'tags' => 'perasaan bersalah, kecintaan Allah, taubat'],
            ['surah' => 4, 'ayat_number' => 17, 'arabic_text' => 'إِنَّمَا التَّوْبَةُ عَلَى اللَّهِ لِلَّذِينَ يَعْمَلُونَ السُّوءَ بِجَهَالَةٍ ثُمَّ يَتُوبُونَ مِنْ قَرِيبٍ', 'translation' => 'Sesungguhnya bertobat kepada Allah itu hanya bagi orang-orang yang membuat kejahatan karena kebodohan, kemudian mereka segera bertobat...', 'tags' => 'perasaan bersalah, kembalinya hamba, kesegeraan taubat'],
            ['surah' => 11, 'ayat_number' => 114, 'arabic_text' => 'إِنَّ الْحَسَنَاتِ يُذْهِبْنَ السَّيِّئَاتِ ۚ ذَٰلِكَ ذِكْرَىٰ لِلذَّاكِرِينَ', 'translation' => '...Sesungguhnya perbuatan-perbuatan baik itu menghapus kesalahan-kesalahan (perbuatan buruk). Itulah pengingat bagi orang-orang yang ingat.', 'tags' => 'perasaan bersalah, penebusan dosa, amal kebaikan'],
            ['surah' => 40, 'ayat_number' => 3, 'arabic_text' => 'غَافِرِ الذَّنْبِ وَقَابِلِ التَّوْبِ شَدِيدِ الْعِقَابِ ذِي الطَّوْلِ', 'translation' => '(Allah) Yang Mengampuni dosa dan Menerima tobat, keras hukuman-Nya, Yang memiliki karunia...', 'tags' => 'perasaan bersalah, penerima taubat, keagungan Allah'],
            ['surah' => 5, 'ayat_number' => 39, 'arabic_text' => 'فَمَنْ تَابَ مِنْ بَعْدِ ظُلْمِهِ وَأَصْلَحَ فَإِنَّ اللَّهَ يَتُوبُ عَلَيْهِ ۗ إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ', 'translation' => 'Maka barangsiapa bertobat setelah melakukan kezaliman itu dan memperbaiki diri, maka sesungguhnya Allah menerima tobatnya...', 'tags' => 'perasaan bersalah, perbaikan diri, ampunan'],
            ['surah' => 9, 'ayat_number' => 118, 'arabic_text' => 'وَعَلَى الثَّلَاثَةِ الَّذِينَ خُلِّفُوا حَتَّىٰ إِذَا ضَاقَتْ عَلَيْهِمُ الْأَرْضُ بِمَا رَحُبَتْ وَضَاقَتْ عَلَيْهِمْ أَنْفُسُهُمْ وَظَنُّوا أَنْ لَا مَلْجَأَ مِنَ اللَّهِ إِلَّا إِلَيْهِ ثُمَّ تَابَ عَلَيْهِمْ لِيَتُوبُوا', 'translation' => 'Dan terhadap tiga orang yang ditangguhkan (penerimaan tobatnya), hingga bumi terasa sempit oleh mereka padahal bumi itu luas, dan jiwa mereka pun telah terasa sempit oleh mereka... kemudian Allah menerima tobat mereka...', 'tags' => 'perasaan bersalah, kesesakan batin, penyesalan mendalam'],
            ['surah' => 9, 'ayat_number' => 104, 'arabic_text' => 'أَلَمْ يَعْلَمُوا أَنَّ اللَّهَ هُوَ يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ وَيَأْخُذُ الصَّدَقَاتِ', 'translation' => 'Tidakkah mereka mengetahui, bahwa Allah menerima tobat dari hamba-hamba-Nya dan menerima sedekah...', 'tags' => 'perasaan bersalah, penerimaan taubat, penenteram jiwa'],

            ['surah' => 20, 'ayat_number' => 82, 'arabic_text' => 'وَإِنِّي لَغَفَّارٌ لِمَنْ تَابَ وَآمَنَ وَعَمِلَ صَالِحًا ثُمَّ اهْتَدَىٰ', 'translation' => 'Dan sungguh, Aku Maha Pengampun bagi yang bertobat, beriman, dan berbuat kebajikan, kemudian tetap di jalan yang benar.', 'tags' => 'perasaan bersalah, janji ampunan, konsistensi'],
            ['surah' => 42, 'ayat_number' => 25, 'arabic_text' => 'وَهُوَ الَّذِي يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ وَيَعْفُو عَنِ السَّيِّئَاتِ وَيَعْلَمُ مَا تَفْعَلُونَ', 'translation' => 'Dan Dialah yang menerima tobat dari hamba-hamba-Nya dan memaafkan kesalahan-kesalahan dan mengetahui apa yang kamu kerjakan.', 'tags' => 'perasaan bersalah, maaf Allah, peleburan kesalahan'],
            ['surah' => 12, 'ayat_number' => 97, 'arabic_text' => 'قَالُوا يَا أَبَانَا اسْتَغْفِرْ لَنَا ذُنُوبَنَا إِنَّا كُنَّا خَاطِئِينَ', 'translation' => 'Mereka berkata: \'Wahai ayah kami! Mohonkanlah ampunan untuk kami atas dosa-dosa kami, sesungguhnya kami adalah orang-orang yang bersalah.\'', 'tags' => 'perasaan bersalah, saudara Nabi Yusuf, pengakuan bersalah'],
            ['surah' => 12, 'ayat_number' => 98, 'arabic_text' => 'قَالَ سَوْفَ أَسْتَغْفِرُ لَكُمْ رَبِّي ۖ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ', 'translation' => 'Dia (Yakub) berkata: \'Aku akan memohonkan ampunan bagimu kepada Tuhanku. Sungguh, Dialah Yang Maha Pengampun lagi Maha Penyayang.\'', 'tags' => 'perasaan bersalah, permintaan maaf, ampunan'],
            ['surah' => 7, 'ayat_number' => 153, 'arabic_text' => 'وَالَّذِينَ عَمِلُوا السَّيِّئَاتِ ثُمَّ تَابُوا مِنْ بَعْدِهَا وَآمَنُوا إِنَّ رَبَّكَ مِنْ بَعْدِهَا لَغَفُورٌ رَحِيمٌ', 'translation' => 'Dan orang-orang yang telah mengerjakan kejahatan, kemudian bertobat sesudah itu dan beriman; sesungguhnya Tuhanmu setelah itu Maha Pengampun lagi Maha Penyayang.', 'tags' => 'perasaan bersalah, perbaikan, ampunan Allah'],
            ['surah' => 6, 'ayat_number' => 54, 'arabic_text' => 'كَتَبَ رَبُّكُمْ عَلَىٰ نَفْسِهِ الرَّحْمَةَ ۖ أَنَّهُ مَنْ عَمِلَ مِنْكُمْ سُوءًا بِجَهَالَةٍ ثُمَّ تَابَ مِنْ بَعْدِهِ وَأَصْلَحَ فَأَنَّهُ غَفُورٌ رَحِيمٌ', 'translation' => '...Tuhanmu telah menetapkan sifat kasih sayang pada diri-Nya, (yaitu) barangsiapa di antara kamu yang berbuat kejahatan karena kebodohan, kemudian bertobat setelah itu dan memperbaiki diri, maka sungguh Allah Maha Pengampun lagi Maha Penyayang.', 'tags' => 'perasaan bersalah, rahmat Allah, penerimaan'],
            ['surah' => 15, 'ayat_number' => 49, 'arabic_text' => 'نَبِّئْ عِبَادِي أَنِّي أَنَا الْغَفُورُ الرَّحِيمُ', 'translation' => 'Kabarkanlah kepada hamba-hamba-Ku, bahwa sesungguhnya Akulah Yang Maha Pengampun lagi Maha Penyayang.', 'tags' => 'perasaan bersalah, penghibur batin, kabar gembira'],
            ['surah' => 2, 'ayat_number' => 286, 'arabic_text' => 'رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِينَا أَوْ أَخْطَأْنَا', 'translation' => '...Ya Tuhan kami, janganlah Engkau hukum kami jika kami lupa atau kami melakukan kesalahan...', 'tags' => 'perasaan bersalah, kekhilafan, doa permohonan ampun'],
            ['surah' => 3, 'ayat_number' => 16, 'arabic_text' => 'الَّذِينَ يَقُولُونَ رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ', 'translation' => '(yaitu) orang-orang yang berdoa: \'Ya Tuhan kami, sungguh kami telah beriman, maka ampunilah dosa-dosa kami dan lindungilah kami dari azab neraka.\'', 'tags' => 'perasaan bersalah, doa hamba, ampunan dosa'],
            ['surah' => 3, 'ayat_number' => 193, 'arabic_text' => 'رَبَّنَا فَاغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا وَتَوَفَّنَا مَعَ الْأَبْرَارِ', 'translation' => '...Ya Tuhan kami, ampunilah dosa-dosa kami dan hapuskanlah kesalahan-kesalahan kami, dan matikanlah kami beserta orang-orang yang berbakti.', 'tags' => 'perasaan bersalah, penyesalan, pemaafan'],
            ['surah' => 71, 'ayat_number' => 10, 'arabic_text' => 'فَقُلْتُ اسْتَغْفِرُوا رَبَّكُمْ إِنَّهُ كَانَ غَفَّارًا', 'translation' => 'Maka aku berkata (kepada mereka): \'Mohonlah ampunan kepada Tuhanmu, sungguh, Dia Maha Pengampun.\'', 'tags' => 'perasaan bersalah, anjuran istighfar, Nabi Nuh'],
            ['surah' => 11, 'ayat_number' => 3, 'arabic_text' => 'وَأَنِ اسْتَغْفِرُوا رَبَّكُمْ ثُمَّ تُوبُوا إِلَيْهِ يُمَتِّعْكُمْ مَتَاعًا حَسَنًا', 'translation' => 'Dan hendaklah kamu memohon ampunan kepada Tuhanmu dan bertobat kepada-Nya, niscaya Dia akan memberi kenikmatan yang baik kepadamu...', 'tags' => 'perasaan bersalah, istighfar, kelapangan hidup'],
            ['surah' => 11, 'ayat_number' => 90, 'arabic_text' => 'وَاسْتَغْفِرُوا رَبَّكُمْ ثُمَّ تُوبُوا إِلَيْهِ ۚ إِنَّ رَبِّي رَحِيمٌ وَدُودٌ', 'translation' => 'Dan mohonlah ampunan kepada Tuhanmu, kemudian bertobatlah kepada-Nya. Sungguh, Tuhanku Maha Penyayang lagi Maha Pengasih.', 'tags' => 'perasaan bersalah, kasih sayang, istighfar'],
            ['surah' => 24, 'ayat_number' => 31, 'arabic_text' => 'وَتُوبُوا إِلَى اللَّهِ جَمِيعًا أَيُّهَ الْمُؤْمِنُونَ لَعَلَّكُمْ تُفْلِحُونَ', 'translation' => '...Dan bertobatlah kamu sekalian kepada Allah, wahai orang-orang yang beriman, agar kamu beruntung.', 'tags' => 'perasaan bersalah, perintah taubat, keberuntungan'],
            ['surah' => 27, 'ayat_number' => 44, 'arabic_text' => 'قَالَتْ رَبِّ إِنِّي ظَلَمْتُ نَفْسِي وَأَسْلَمْتُ مَعَ سُلَيْمَانَ لِلَّهِ رَبِّ الْعَالَمِينَ', 'translation' => '...Dia (Ratu Balqis) berkata: \'Ya Tuhanku, sungguh aku telah menzalimi diriku sendiri dan aku berserah diri bersama Sulaiman kepada Allah, Tuhan seluruh alam.\'', 'tags' => 'perasaan bersalah, penyesalan, Balqis, kepasrahan'],

            ['surah' => 12, 'ayat_number' => 29, 'arabic_text' => 'وَاسْتَغْفِرِي لِذَنْبِكِ ۖ إِنَّكِ كُنْتِ مِنَ الْخَاطِئِينَ', 'translation' => '...Dan (wahai Zulaikha) mohonlah ampunan atas dosamu, karena sesungguhnya engkau termasuk orang-orang yang bersalah.', 'tags' => 'perasaan bersalah, teguran dosa, permohonan maaf'],
            ['surah' => 25, 'ayat_number' => 71, 'arabic_text' => 'وَمَنْ تَابَ وَعَمِلَ صَالِحًا فَإِنَّهُ يَتُوبُ إِلَى اللَّهِ مَتَابًا', 'translation' => 'Dan barangsiapa bertobat dan mengerjakan kebajikan, maka sesungguhnya dia bertobat kepada Allah dengan tobat yang sebenar-benarnya.', 'tags' => 'perasaan bersalah, kelurusan niat, kesungguhan'],
            ['surah' => 41, 'ayat_number' => 6, 'arabic_text' => 'فَاسْتَقِيمُوا إِلَيْهِ وَاسْتَغْفِرُوهُ', 'translation' => '...maka tetaplah di jalan yang lurus menuju kepada-Nya dan mohonlah ampunan kepada-Nya...', 'tags' => 'perasaan bersalah, istiqamah, istighfar'],
            ['surah' => 47, 'ayat_number' => 19, 'arabic_text' => 'وَاسْتَغْفِرْ لِذَنْبِكَ وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ', 'translation' => '...dan mohonlah ampunan atas dosamu dan atas (dosa) orang-orang mukmin, laki-laki dan perempuan...', 'tags' => 'perasaan bersalah, istighfar, solidaritas mukmin'],
            ['surah' => 110, 'ayat_number' => 3, 'arabic_text' => 'فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا', 'translation' => 'maka bertasbihlah dengan memuji Tuhanmu dan mohonlah ampunan kepada-Nya. Sungguh, Dia Maha Penerima tobat.', 'tags' => 'perasaan bersalah, tasbih, penutup amalan'],
        ];

        $hadiths = [
            ['arabic_text' => 'الإِثْمُ مَا حَاكَ فِي صَدْرِكَ وَكَرِهْتَ أَنْ يَطَّلِعَ عَلَيْهِ النَّاسُ', 'translation' => 'Dosa adalah apa yang meragukan/mengganjal (menimbulkan rasa bersalah) di dalam dadamu dan engkau benci jika hal itu diketahui oleh orang lain.', 'book' => 'Muslim', 'number' => '2553', 'source' => 'HR. Muslim no. 2553'],
            ['arabic_text' => 'النَّدَمُ تَوْبَةٌ', 'translation' => 'Penyesalan (rasa bersalah atas dosa) adalah hakikat dari tobat.', 'book' => 'Ibn Majah, Ahmad', 'number' => '4252', 'source' => 'HR. Ibn Majah no. 4252 & Ahmad'],
            ['arabic_text' => 'التَّائِبُ مِنَ الذَّنْبِ كَمَنْ لاَ ذَنْبَ لَهُ', 'translation' => 'Orang yang bertobat dari dosanya adalah seperti orang yang tidak memiliki dosa sama sekali.', 'book' => 'Ibn Majah', 'number' => '4250', 'source' => 'HR. Ibn Majah no. 4250'],
            ['arabic_text' => 'كُلُّ ابْنِ آدَمَ خَطَّاءٌ وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ', 'translation' => 'Setiap anak Adam pasti sering berbuat salah/dosa, dan sebaik-baik orang yang berbuat salah adalah mereka yang bertobat.', 'book' => 'Tirmidzi, Ibn Majah', 'number' => '2499', 'source' => 'HR. Tirmidzi no. 2499 & Ibn Majah'],
            ['arabic_text' => 'يَا ابْنَ آدَمَ إِنَّكَ مَا دَعَوْتَنِي وَرَجَوْتَنِي غَفَرْتُ لَكَ عَلَى مَا كَانَ مِنْكَ وَلاَ أُبَالِي', 'translation' => 'Wahai anak Adam, sesungguhnya selagi engkau berdoa kepada-Ku dan mengharapkan-Ku, Aku akan mengampunimu atas dosa apa pun yang ada padamu dan Aku tidak peduli.', 'book' => 'Tirmidzi', 'number' => '3540', 'source' => 'HR. Tirmidzi no. 3540'],
            ['arabic_text' => 'يَا ابْنَ آدَمَ لَوْ بَلَغَتْ ذُنُوبُكَ عَنَانَ السَّمَاءِ ثُمَّ اسْتَغْفَرْتَنِي غَفَرْتُ لَكَ', 'translation' => 'Wahai anak Adam, seandainya dosa-dosamu menumpuk setinggi langit kemudian engkau memohon ampunan kepada-Ku, niscaya Aku ampuni engkau.', 'book' => 'Tirmidzi', 'number' => '3540', 'source' => 'HR. Tirmidzi no. 3540'],
            ['arabic_text' => 'لَلَّهُ أَشَدُّ فَرَحًا بِتَوْبَةِ عَبْدِهِ حِينَ يَتُوبُ إِلَيْهِ مِنْ أَحَدِكُمْ كَانَ عَلَى رَاحِلَتِهِ بِأَرْضٍ فَلاَةٍ فَأَضَلَّتْهُ...', 'translation' => 'Sungguh, Allah lebih gembira dengan tobat hamba-Nya daripada kegembiraan seseorang yang kehilangan untanya di padang pasir lalu menemukannya kembali...', 'book' => 'Bukhari, Muslim', 'number' => '6309, 2747', 'source' => 'HR. Bukhari no. 6309 & Muslim no. 2747'],
            ['arabic_text' => 'إِنَّ اللَّهَ يَبْسُطُ يَدَهُ بِاللَّيْلِ لِيَتُوبَ مُسِيءُ النَّهَارِ وَيَبْسُطُ يَدَهُ بِالنَّهَارِ لِيَتُوبَ مُسِيءُ اللَّيْلِ', 'translation' => 'Sesungguhnya Allah membentangkan tangan-Nya pada malam hari untuk menerima tobat orang yang berbuat dosa di siang hari, dan membentangkan tangan-Nya pada siang hari untuk menerima tobat orang yang berbuat dosa di malam hari...', 'book' => 'Muslim', 'number' => '2759', 'source' => 'HR. Muslim no. 2759'],
            ['arabic_text' => 'سَيِّدُ الاِسْتِغْفَارِ: اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ... أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي', 'translation' => 'Pimpinan istighfar: \'Ya Allah, Engkau adalah Tuhanku... Aku mengakui nikmat-Mu kepadaku dan aku mengakui dosaku (rasa bersalahku), maka ampunilah aku...\'', 'book' => 'Bukhari', 'number' => '6306', 'source' => 'HR. Bukhari no. 6306'],
            ['arabic_text' => 'مَا مِنْ عَبْدٍ يُذْنِبُ ذَنْبًا فَيُحْسِنُ الطُّهُورَ ثُمَّ يَقُومُ فَيُصَلِّي رَكْعَتَيْنِ ثُمَّ يَسْتَغْفِرُ اللَّهَ إِلاَّ غَفَرَ اللَّهُ لَهُ', 'translation' => 'Tidak ada seorang hamba pun yang berbuat dosa, lalu ia berwudu dengan baik kemudian bangkit shalat dua rakaat lalu memohon ampunan kepada Allah, melainkan Allah pasti mengampuninya.', 'book' => 'Abu Dawud, Tirmidzi', 'number' => '1521', 'source' => 'HR. Abu Dawud no. 1521 & Tirmidzi'],
            ['arabic_text' => 'وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا، وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ', 'translation' => '...Dan iringilah perbuatan buruk (yang menimbulkan rasa bersalah) dengan perbuatan baik, niscaya kebaikan itu akan menghapusnya, serta berakhlaklah kepada manusia dengan akhlak yang baik.', 'book' => 'Tirmidzi', 'number' => '1987', 'source' => 'HR. Tirmidzi no. 1987'],
            ['arabic_text' => 'لَوْ لَمْ تُذْنِبُوا لَذَهَبَ اللَّهُ بِكُمْ وَلَجَاءَ بِقَوْمٍ يُذْنِبُونَ فَيَسْتَغْفِرُونَ اللَّهَ فَيَغْفِرُ لَهُمْ', 'translation' => 'Seandainya kalian tidak pernah berbuat dosa, niscaya Allah akan memusnahkan kalian dan menggantikan dengan kaum yang berbuat dosa lalu mereka memohon ampunan kepada Allah, dan Allah pun mengampuni mereka.', 'book' => 'Muslim', 'number' => '2749', 'source' => 'HR. Muslim no. 2749'],
            ['arabic_text' => 'إِنَّ الْمُؤْمِنَ يَرَى ذُنُوبَهُ كَأَنَّهُ قَاعِدٌ تَحْتَ جَبَلٍ يَخَافُ أَنْ يَقَعَ عَلَيْهِ', 'translation' => 'Sesungguhnya seorang mukmin melihat dosa-dosanya (merasakan beban bersalah) seolah-olah ia duduk di bawah gunung yang ia takuti akan menimpanya...', 'book' => 'Bukhari', 'number' => '6308', 'source' => 'HR. Bukhari no. 6308'],
            ['arabic_text' => 'إِنَّ عَبْدًا أَذْنَبَ ذَنْبًا فَقَالَ رَبِّ أَذْنَبْتُ فَاغْفِرْ لِي... قَالَ اللَّهُ: عَلِمَ عَبْدِي أَنَّ لَهُ رَبًّا يَغْفِرُ الذَّنْبَ... قَدْ غَفَرْتُ لِعَبْدِي', 'translation' => 'Seorang hamba berbuat dosa lalu berdoa: \'Ya Tuhan, aku telah berbuat dosa, ampunilah aku.\' Allah berfirman: \'Hamba-Ku tahu bahwa ia memiliki Tuhan yang mengampuni dosa... Sungguh Aku telah mengampuni hamba-Ku.\'', 'book' => 'Bukhari, Muslim', 'number' => '7507', 'source' => 'HR. Bukhari no. 7507 & Muslim'],
            ['arabic_text' => 'مَنْ لَزِمَ الاِسْتِغْفَارَ جَعَلَ اللَّهُ لَهُ مِنْ كُلِّ ضِيقٍ مَخْرَجًا وَمِنْ كُلِّ هَمٍّ فَرَجًا', 'translation' => 'Barangsiapa melazimkan (merutinkan) istighfar, niscaya Allah jadikan baginya jalan keluar dari setiap kesempitan dan kelapangan dari setiap duka cita/rasa bersalah.', 'book' => 'Abu Dawud', 'number' => '1518', 'source' => 'HR. Abu Dawud no. 1518'],
        ];

        foreach ($quranVerses as $verse) {
            $this->db->table('quran_verses')->insert([
                'surah'       => $verse['surah'],
                'ayat_number' => $verse['ayat_number'],
                'arabic_text' => $verse['arabic_text'],
                'translation' => $verse['translation'],
                'source'      => "Al-Qur'an",
                'tags'        => $verse['tags'],
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ]);
        }

        foreach ($hadiths as $hadith) {
            $this->db->table('hadiths')->insert([
                'arabic_text' => $hadith['arabic_text'],
                'translation' => $hadith['translation'],
                'book'        => $hadith['book'],
                'number'      => $hadith['number'],
                'source'      => $hadith['source'],
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ]);
        }

        echo 'Seeded ' . count($quranVerses) . ' quran verses and ' . count($hadiths) . ' hadiths (bersalah).' . PHP_EOL;
    }
}
