<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ContentMaluSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $quranVerses = [

            ['surah' => 28, 'ayat_number' => 25, 'arabic_text' => 'فَجَاءَتْهُ إِحْدَاهُمَا تَمْشِي عَلَى اسْتِحْيَاءٍ', 'translation' => 'Kemudian datanglah kepada Musa salah seorang dari kedua perempuan itu berjalan dengan malu-malu...', 'tags' => 'malu, adab wanita, iffah, kesopanan'],
            ['surah' => 7, 'ayat_number' => 22, 'arabic_text' => 'فَلَمَّا ذَاقَا الشَّجَرَةَ بَدَتْ لَهُمَا سَوْآتُهُمَا وَطَفِقَا يَخْصِفَانِ عَلَيْهِمَا مِنْ وَرَقِ الْجَنَّةِ', 'translation' => '...Maka ketika keduanya telah merasa manisnya pohon itu, tampaklah bagi keduanya aurat-auratnya, dan mulailah keduanya menutupi dengan daun-daun surga.', 'tags' => 'malu, aurat, fitrah manusia, Nabi Adam'],
            ['surah' => 20, 'ayat_number' => 121, 'arabic_text' => 'فَأَكَلَا مِنْهَا فَبَدَتْ لَهُمَا سَوْآتُهُمَا وَطَفِقَا يَخْصِفَانِ عَلَيْهِمَا مِنْ وَرَقِ الْجَنَّةِ', 'translation' => 'Lalu keduanya memakannya, maka tampaklah bagi keduanya aurat-auratnya dan mulailah keduanya menutupi dengan daun-daun surga...', 'tags' => 'malu, menutup aurat, fitrah, kesucian'],
            ['surah' => 24, 'ayat_number' => 30, 'arabic_text' => 'قُلْ لِلْمُؤْمِنِينَ يَغُضُّوا مِنْ أَبْصَارِهِمْ وَيَحْفَظُوا فُرُوجَهُمْ ۚ ذَٰلِكَ أَزْكَىٰ لَهُمْ', 'translation' => 'Katakanlah kepada laki-laki yang beriman, agar mereka menjaga pandangannya, dan memelihara kemaluannya; yang demikian itu lebih suci bagi mereka...', 'tags' => 'malu, menjaga pandangan, iffah, kesucian'],
            ['surah' => 24, 'ayat_number' => 31, 'arabic_text' => 'وَقُلْ لِلْمُؤْمِنَاتِ يَغْضُضْنَ مِنْ أَبْصَارِهِنَّ وَيَحْفَظْنَ فُرُوجَهُنَّ وَلَا يُبْدِينَ زِينَتَهُنَّ إِلَّا مَا ظَهَرَ مِنْهَا', 'translation' => 'Dan katakanlah kepada para perempuan yang beriman, agar mereka menjaga pandangannya, dan memelihara kemaluannya, dan janganlah menampakkan perhiasannya (auratnya), kecuali yang (biasa) tampak darinya...', 'tags' => 'malu, adab wanita, menutup aurat, kehormatan'],
            ['surah' => 33, 'ayat_number' => 53, 'arabic_text' => 'إِنَّ ذَٰلِكُمْ كَانَ يُؤْذِي النَّبِيَّ فَيَسْتَحْيِي مِنْكُمْ ۖ وَاللَّهُ لَا يَسْتَحْيِي مِنَ الْحَقِّ', 'translation' => '...Sesungguhnya yang demikian itu akan menyakiti hati Nabi lalu dia malu kepadamu (untuk menyuruh kamu keluar), dan Allah tidak malu (menerangkan) yang benar...', 'tags' => 'malu, akhlak Nabi, adab bertamu, kebenaran'],
            ['surah' => 33, 'ayat_number' => 59, 'arabic_text' => 'يَا أَيُّهَا النَّبِيُّ قُلْ لِأَزْوَاجِكَ وَبَنَاتِكَ وَنِسَاءِ الْمُؤْمِنِينَ يُدْنِينَ عَلَيْهِنَّ مِنْ جَلَابِيبِهِنَّ ۚ ذَٰلِكَ أَدْنَىٰ أَنْ يُعْرَفْنَ فَلَا يُؤْذَيْنَ', 'translation' => 'Wahai Nabi! Katakanlah kepada istri-istrimu, anak-anak perempuanmu dan istri-istri orang mukmin, \'Hendaklah mereka mengulurkan jilbabnya ke seluruh tubuh mereka.\' Yang demikian itu agar mereka lebih mudah untuk dikenal, sehingga mereka tidak diganggu...', 'tags' => 'malu, jilbab, perlindungan, iffah'],
            ['surah' => 7, 'ayat_number' => 26, 'arabic_text' => 'يَا بَنِي آدَمَ قَدْ أَنْزَلْنَا عَلَيْكُمْ لِبَاسًا يُوَارِي سَوْآتِكُمْ وَرِيشًا ۖ وَلِبَاسُ التَّقْوَىٰ ذَٰلِكَ خَيْرٌ', 'translation' => 'Wahai anak cucu Adam! Sesungguhnya Kami telah menyediakan pakaian untuk menutupi auratmu dan untuk perhiasan bagimu. Tetapi pakaian takwa, itulah yang terbaik...', 'tags' => 'malu, menutup aurat, pakaian takwa, kehormatan'],
            ['surah' => 2, 'ayat_number' => 273, 'arabic_text' => 'يَحْسَبُهُمُ الْجَاهِلُ أَغْنِيَاءَ مِنَ التَّعَفُّفِ تَعْرِفُهُمْ بِسِيمَاهُمْ لَا يَسْأَلُونَ النَّاسَ إِلْحَافًا', 'translation' => '...Orang yang tidak tahu mengira mereka adalah orang-orang kaya karena mereka memelihara diri dari meminta-minta (karena rasa malu). Engkau (Muhammad) mengenal mereka dari ciri-cirinya, mereka tidak meminta kepada manusia secara mendesak...', 'tags' => 'malu, menjaga kehormatan, ta\'affuf, tidak meminta-minta'],
            ['surah' => 23, 'ayat_number' => 5, 'arabic_text' => 'وَالَّذِينَ هُمْ لِفُرُوجِهِمْ حَافِظُونَ', 'translation' => 'dan orang-orang yang memelihara kemaluannya,', 'tags' => 'malu, kesucian, iffah, sifat mukmin'],
            ['surah' => 70, 'ayat_number' => 29, 'arabic_text' => 'وَالَّذِينَ هُمْ لِفُرُوجِهِمْ حَافِظُونَ', 'translation' => 'Dan orang-orang yang memelihara kemaluannya,', 'tags' => 'malu, menjaga kehormatan, dorongan moral'],
            ['surah' => 2, 'ayat_number' => 26, 'arabic_text' => 'إِنَّ اللَّهَ لَا يَسْتَحْيِي أَنْ يَضْرِبَ مَثَلًا مَا بَعُوضَةً فَمَا فَوْقَهَا', 'translation' => 'Sesungguhnya Allah tidak malu membuat perumpamaan berupa nyamuk atau yang lebih kecil dari itu...', 'tags' => 'malu, kebenaran, hikmah perumpamaan'],
            ['surah' => 24, 'ayat_number' => 58, 'arabic_text' => 'يَا أَيُّهَا الَّذِينَ آمَنُوا لِيَسْتَأْذِنْكُمُ الَّذِينَ مَلَكَتْ أَيْمَانُكُمْ وَالَّذِينَ لَمْ يَبْلُغُوا الْحُلُمَ مِنْكُمْ ثَلَاثَ مَرَّاتٍ', 'translation' => 'Wahai orang-orang yang beriman! Hendaklah hamba sahaya yang kamu miliki dan orang-orang yang belum balig di antara kamu, meminta izin kepadamu tiga kali (dalam sehari)...', 'tags' => 'malu, privasi, adab meminta izin, menjaga aurat'],

            ['surah' => 24, 'ayat_number' => 59, 'arabic_text' => 'وَإِذَا بَلَغَ الْأَطْفَالُ مِنْكُمُ الْحُلُمَ فَلْيَسْتَأْذِنُوا كَمَا اسْتَأْذَنَ الَّذِينَ مِنْ قَبْلِهِمْ', 'translation' => 'Dan apabila anak-anakmu telah sampai umur balig, maka hendaklah mereka (juga) meminta izin, seperti orang-orang yang sebelum mereka meminta izin...', 'tags' => 'malu, adab rumah tangga, kehormatan privasi'],
            ['surah' => 24, 'ayat_number' => 27, 'arabic_text' => 'يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَدْخُلُوا بُيُوتًا غَيْرَ بُيُوتِكُمْ حَتَّىٰ تَسْتَأْنِسُوا وَتُسَلِّمُوا عَلَىٰ أَهْلِهَا', 'translation' => 'Wahai orang-orang yang beriman! Janganlah kamu memasuki rumah yang bukan rumahmu sebelum meminta izin dan memberi salam kepada penghuninya...', 'tags' => 'malu, adab bertamu, menjaga pandangan'],
            ['surah' => 24, 'ayat_number' => 28, 'arabic_text' => 'فَإِنْ لَمْ تَجِدُوا فِيهَا أَحَدًا فَلَا تَدْخُلُوهَا حَتَّىٰ يُؤْذَنَ لَكُمْ ۖ وَإِنْ قِيلَ لَكُمُ ارْجِعُوا فَارْجِعُوا', 'translation' => 'Dan jika kamu tidak menemui seorang pun di dalamnya, maka janganlah kamu masuk sebelum kamu mendapat izin. Dan jika dikatakan kepadamu, \'Kembalilah!\' Maka hendaklah kamu kembali...', 'tags' => 'malu, tenggang rasa, menghormati hak orang lain'],
            ['surah' => 33, 'ayat_number' => 35, 'arabic_text' => 'وَالْحَافِظِينَ فُرُوجَهُمْ وَالْحَافِظَاتِ وَالذَّاكِرِينَ اللَّهَ كَثِيرًا وَالذَّاكِرَاتِ أَعَدَّ اللَّهُ لَهُمْ مَغْفِرَةً وَأَجْرًا عَظِيمًا', 'translation' => '...laki-laki dan perempuan yang memelihara kehormatannya, laki-laki dan perempuan yang banyak menyebut (nama) Allah, Allah telah menyediakan untuk mereka ampunan dan pahala yang besar.', 'tags' => 'malu, kesucian, ampunan, pahala'],
            ['surah' => 66, 'ayat_number' => 12, 'arabic_text' => 'وَمَرْيَمَ ابْنَتَ عِمْرَانَ الَّتِي أَحْصَنَتْ فَرْجَهَا فَنَفَخْنَا فِيهِ مِنْ رُوحِنَا', 'translation' => 'Dan Maryam putri Imran yang memelihara kehormatannya, lalu Kami tiupkan ke dalam rahimnya sebagian dari roh (ciptaan) Kami...', 'tags' => 'malu, kesucian Maryam, iffah, teladan'],
            ['surah' => 21, 'ayat_number' => 91, 'arabic_text' => 'وَالَّتِي أَحْصَنَتْ فَرْجَهَا فَنَفَخْنَا فِيهَا مِنْ رُوحِنَا وَجَعَلْنَاهَا وَابْنَهَا آيَةً لِلْعَالَمِينَ', 'translation' => 'Dan (ingatlah kisah Maryam) yang telah memelihara kehormatannya, lalu Kami tiupkan ke dalam (tubuh)nya roh dari Kami dan Kami jadikan dia dan anaknya tanda (kekuasaan Allah) bagi seluruh alam.', 'tags' => 'malu, menjaga diri, kehormatan wanita'],
            ['surah' => 4, 'ayat_number' => 25, 'arabic_text' => 'مُحْصَنَاتٍ غَيْرَ مُسَافِحَاتٍ وَلَا مُتَّخِذَاتِ أَخْدَانٍ', 'translation' => '...sedang mereka pun wanita-wanita yang memelihara diri, bukan pezina dan bukan pula wanita yang mengambil laki-laki lain sebagai piaraannya...', 'tags' => 'malu, pergaulan, memelihara diri, pernikahan'],
            ['surah' => 5, 'ayat_number' => 5, 'arabic_text' => 'وَالْمُحْصَنَاتُ مِنَ الْمُؤْمِنَاتِ وَالْمُحْصَنَاتُ مِنَ الَّذِينَ أُوتُوا الْكِتَابَ مِنْ قَبْلِكُمْ إِذَا آتَيْتُمُوهُنَّ أُجُورَهُنَّ مُحْصِنِينَ غَيْرَ مُسَافِحِينَ وَلَا مُتَّخِذِي أَخْدَانٍ', 'translation' => '...Dan (dihalalkan bagimu menikahi) wanita-wanita yang menjaga kehormatan di antara wanita-wanita yang beriman... dengan maksud menikahi mereka, bukan dengan maksud berzina dan bukan pula menjadikan mereka gundik...', 'tags' => 'malu, kehormatan, pernikahan suci'],
            ['surah' => 24, 'ayat_number' => 33, 'arabic_text' => 'وَلْيَسْتَعْفِفِ الَّذِينَ لَا يَجِدُونَ نِكَاحًا حَتَّىٰ يُغْنِيَهُمُ اللَّهُ مِنْ فَضْلِهِ', 'translation' => 'Dan orang-orang yang belum mampu menikah hendaklah menjaga kesucian (diri)nya, sampai Allah memberi kemampuan kepada mereka dengan karunia-Nya...', 'tags' => 'malu, ta\'affuf, menjaga kesucian diri'],
            ['surah' => 24, 'ayat_number' => 60, 'arabic_text' => 'وَالْقَوَاعِدُ مِنَ النِّسَاءِ اللَّاتِي لَا يَرْجُونَ نِكَاحًا فَلَيْسَ عَلَيْهِنَّ جُنَاحٌ أَنْ يَضَعْنَ ثِيَابَهُنَّ غَيْرَ مُتَبَرِّجَاتٍ بِزِينَةٍ ۖ وَأَنْ يَسْتَعْفِفْنَ خَيْرٌ لَهُنَّ', 'translation' => 'Dan para perempuan tua yang telah berhenti (dari haid dan beranak) yang tidak ingin menikah (lagi), tidak ada dosa bagi mereka menanggalkan pakaian (luar) mereka dengan tidak (maksud) menampakkan perhiasan; tetapi memelihara kesucian (dan rasa malu) adalah lebih baik bagi mereka...', 'tags' => 'malu, ta\'affuf, kesopanan, wanita tua'],
            ['surah' => 40, 'ayat_number' => 19, 'arabic_text' => 'يَعْلَمُ خَائِنَةَ الْأَعْيُنِ وَمَا تُخْفِي الصُّدُورُ', 'translation' => 'Dia mengetahui (pandangan) mata yang khianat dan apa yang disembunyikan oleh hati.', 'tags' => 'malu kepada Allah, pengawasan Allah, pandangan mata'],
            ['surah' => 10, 'ayat_number' => 61, 'arabic_text' => 'وَمَا تَكُونُ فِي شَأْنٍ وَمَا تَتْلُو مِنْهُ مِنْ قُرْآنٍ وَلَا تَعْمَلُونَ مِنْ عَمَلٍ إِلَّا كُنَّا عَلَيْكُمْ شُهُودًا إِذْ تُفِيضُونَ فِيهِ', 'translation' => 'Dan tidakkah engkau berada dalam suatu urusan, dan tidak membaca suatu ayat Al-Qur\'an, dan tidak pula kamu melakukan suatu pekerjaan, melainkan Kami menjadi saksi atasmu ketika kamu melakukannya...', 'tags' => 'malu kepada Allah, merasa diawasi, muraqabah'],
        ];

        $hadiths = [
            ['arabic_text' => 'الإِيمَانُ بِضْعٌ وَسَبْعُونَ أَوْ بِضْعٌ وَسِتُّونَ شُعْبَةً، فَأَفْضَلُهَا قَوْلُ لاَ إِلَهَ إِلاَّ اللَّهُ، وَأَدْنَاهَا إِمَاطَةُ الأَذَى عَنِ الطَّرِيقِ، وَالْحَيَاءُ شُعْبَةٌ مِنَ الإِيمَانِ', 'translation' => 'Iman itu ada 70 atau 60 sekian cabang. Yang paling utama adalah ucapan \'Laa ilaaha illallah\' dan yang paling rendah adalah menyingkirkan gangguan dari jalan. Dan malu adalah salah satu cabang dari iman.', 'book' => 'Bukhari, Muslim', 'number' => '9, 35', 'source' => 'HR. Bukhari no. 9 & Muslim no. 35'],
            ['arabic_text' => 'الْحَيَاءُ لاَ يَأْتِي إِلاَّ بِخَيْرٍ', 'translation' => 'Malu itu tidak mendatangkan sesuatu melainkan kebaikan.', 'book' => 'Bukhari, Muslim', 'number' => '6117, 37', 'source' => 'HR. Bukhari no. 6117 & Muslim no. 37'],
            ['arabic_text' => 'الْحَيَاءُ كُلُّهُ خَيْرٌ', 'translation' => 'Malu itu seluruhnya adalah kebaikan.', 'book' => 'Muslim', 'number' => '37', 'source' => 'HR. Muslim no. 37'],
            ['arabic_text' => 'إِنَّ مِمَّا أَدْرَكَ النَّاسُ مِنْ كَلاَمِ النُّبُوَّةِ الأُولَى: إِذَا لَمْ تَسْتَحْيِ فَاصْنَعْ مَا شِئْتَ', 'translation' => 'Sesungguhnya di antara ajaran yang didapatkan manusia dari perkataan nabi-nabi terdahulu adalah: \'Jika engkau tidak malu, maka berbuatlah sesukamu.\'', 'book' => 'Bukhari', 'number' => '3483', 'source' => 'HR. Bukhari no. 3483'],
            ['arabic_text' => 'الْحَيَاءُ مِنَ الإِيمَانِ، وَالإِيمَانُ فِي الْجَنَّةِ، وَالْبَذَاءُ مِنَ الْجَفَاءِ، وَالْجَفَاءُ فِي النَّارِ', 'translation' => 'Malu itu bagian dari iman, dan iman itu tempatnya di surga. Sedangkan perkataan/perbuatan kotor (kebalikan malu) adalah bagian dari tabiat yang kasar, dan tabiat kasar tempatnya di neraka.', 'book' => 'Tirmidzi, Ahmad', 'number' => '2009', 'source' => 'HR. Tirmidzi no. 2009 & Ahmad'],
            ['arabic_text' => 'إِنَّ اللَّهَ حَيِيٌّ سِتِّيرٌ يُحِبُّ الْحَيَاءَ وَالسَّتْرَ، فَإِذَا اغْتَسَلَ أَحَدُكُمْ فَلْيَسْتَتِرْ', 'translation' => 'Sesungguhnya Allah Maha Pemalu lagi Maha Menutup (aib/aurat). Dia menyukai rasa malu dan tutupan. Maka apabila salah seorang dari kalian mandi, hendaklah ia menutup diri.', 'book' => 'Abu Dawud, An-Nasa\'i', 'number' => '4012', 'source' => 'HR. Abu Dawud no. 4012 & An-Nasa\'i'],
            ['arabic_text' => 'إِنَّ لِكُلِّ دِينٍ خُلُقًا، وَخُلُقُ الإِسْلاَمِ الْحَيَاءُ', 'translation' => 'Sesungguhnya setiap agama memiliki akhlak (ciri khas), dan akhlak Islam adalah rasa malu.', 'book' => 'Ibn Majah, Malik', 'number' => '4181', 'source' => 'HR. Ibn Majah no. 4181 & Malik'],
            ['arabic_text' => 'اسْتَحْيُوا مِنَ اللَّهِ حَقَّ الحَيَاءِ... مَنْ اسْتَحْيَا مِنَ اللَّهِ حَقَّ الحَيَاءِ فَلْيَحْفَظِ الرَّأْسَ وَمَا وَعَى، وَالْبَطْنَ وَمَا حَوَى', 'translation' => 'Malulah kepada Allah dengan sebenar-benar malu. Siapa yang malu kepada Allah dengan sebenar-benarnya, hendaklah ia menjaga kepala dan apa yang dipikirkannya, serta menjaga perut dan apa yang dimasukkannya...', 'book' => 'Tirmidzi', 'number' => '2458', 'source' => 'HR. Tirmidzi no. 2458'],
            ['arabic_text' => 'كَانَ النَّبِيُّ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ أَشَدَّ حَيَاءً مِنَ الْعَذْرَاءِ فِي خِدْرِهَا', 'translation' => 'Nabi SAW adalah orang yang jauh lebih pemalu daripada gadis perawan di dalam pingitannya.', 'book' => 'Bukhari, Muslim', 'number' => '6102, 2320', 'source' => 'HR. Bukhari no. 6102 & Muslim no. 2320'],
            ['arabic_text' => 'أَلاَ أَسْتَحْيِي مِنْ رَجُلٍ تَسْتَحْيِي مِنْهُ الْمَلاَئِكَةُ', 'translation' => '(Mengenai Utsman bin Affan) Rasulullah SAW bersabda: \'Apakah aku tidak malu kepada seorang laki-laki yang para malaikat saja malu kepadanya?\'', 'book' => 'Muslim', 'number' => '2401', 'source' => 'HR. Muslim no. 2401'],
            ['arabic_text' => 'الْحَيَاءُ وَالإِيمَانُ قُرَنَاءُ جَمِيعًا، فَإِذَا رُفِعَ أَحَدُهُمَا رُفِعَ الآخَرُ', 'translation' => 'Malu dan iman itu adalah dua hal yang selalu bergandengan bersama. Jika salah satunya diangkat/hilang, maka hilang pula yang lainnya.', 'book' => 'Al-Hakim', 'number' => null, 'source' => 'HR. Al-Hakim (Al-Mustadrak) & Al-Albani'],
            ['arabic_text' => 'مَا كَانَ الْفُحْشُ فِي شَيْءٍ إِلاَّ شَانَهُ، وَمَا كَانَ الْحَيَاءُ فِي شَيْءٍ إِلاَّ زَانَهُ', 'translation' => 'Tidaklah kekejian/kekasaran berada pada sesuatu melainkan akan memperburuknya, dan tidaklah rasa malu berada pada sesuatu melainkan akan menghiasinya.', 'book' => 'Tirmidzi, Ibn Majah', 'number' => '1974', 'source' => 'HR. Tirmidzi no. 1974 & Ibn Majah'],
            ['arabic_text' => 'دَعْهُ فَإِنَّ الْحَيَاءَ مِنَ الإِيمَانِ', 'translation' => 'Nabi SAW melewati seorang Anshar yang sedang menasihati (menegur) saudaranya karena sifat pemalunya. Maka Rasulullah SAW bersabda: \'Biarkanlah dia, karena sesungguhnya malu itu bagian dari iman.\'', 'book' => 'Bukhari, Muslim', 'number' => '24, 36', 'source' => 'HR. Bukhari no. 24 & Muslim no. 36'],
            ['arabic_text' => 'احْفَظْ عَوْرَتَكَ إِلاَّ مِنْ زَوْجَتِكَ أَوْ مَا مَلَكَتْ يَمِينُكَ', 'translation' => 'Jagalah auratmu kecuali terhadap istrimu atau hamba sahaya yang engkau miliki.', 'book' => 'Abu Dawud, Tirmidzi', 'number' => '4017', 'source' => 'HR. Abu Dawud no. 4017 & Tirmidzi'],
            ['arabic_text' => 'فَاللَّهُ أَحَقُّ أَنْ يُسْتَحْيَا مِنْهُ مِنَ النَّاسِ', 'translation' => '...Maka Allah lebih berhak untuk engkau merasa malu kepada-Nya daripada kepada manusia.', 'book' => 'Abu Dawud, Tirmidzi', 'number' => '4017', 'source' => 'HR. Abu Dawud no. 4017 & Tirmidzi'],
            ['arabic_text' => 'قَدْ أَفْلَحَ مَنْ أَسْلَمَ وَرُزِقَ كَفَافًا وَقَنَّعَهُ اللَّهُ بِمَا آتَاهُ', 'translation' => 'Sungguh beruntung orang yang berserah diri (masuk Islam), diberi rezeki yang cukup, dan dijadikan merasa cukup (serta malu meminta-minta) oleh Allah atas apa yang diberikan kepadanya.', 'book' => 'Muslim', 'number' => '1054', 'source' => 'HR. Muslim no. 1054'],
            ['arabic_text' => 'وَمَنْ يَسْتَعْفِفْ يُعِفَّهُ اللَّهُ، وَمَنْ يَسْتَغْنِ يُغْنِهِ اللَّهُ', 'translation' => 'Barangsiapa yang berusaha menjaga kesucian dirinya (karena malu meminta-minta), maka Allah akan menjaganya. Dan barangsiapa yang merasa cukup, maka Allah akan mencukupkannya.', 'book' => 'Bukhari, Muslim', 'number' => '1427', 'source' => 'HR. Bukhari no. 1427 & Muslim'],
            ['arabic_text' => 'مَا يَزَالُ الرَّجُلُ يَسْأَلُ النَّاسَ حَتَّى يَأْتِيَ يَوْمَ الْقِيَامَةِ لَيْسَ فِي وَجْهِهِ مُزْعَةُ لَحْمٍ', 'translation' => 'Seseorang yang terus-menerus meminta-minta kepada manusia (tanpa rasa malu), ia akan datang pada hari kiamat dalam keadaan tidak ada sepotong daging pun di wajahnya.', 'book' => 'Bukhari, Muslim', 'number' => '1474', 'source' => 'HR. Bukhari no. 1474 & Muslim'],
            ['arabic_text' => 'لَيْسَ الْمِسْكِينُ الَّذِي يَطُوفُ عَلَى النَّاسِ تَرُدُّهُ اللُّقْمَةُ وَاللُّقْمَتَانِ... وَلَكِنَّ الْمِسْكِينَ الَّذِي لاَ يَجِدُ غِنًى... وَلاَ يَسْأَلُ النَّاسَ شَيْئًا', 'translation' => 'Bukanlah orang miskin (sejati) itu orang yang berkeliling meminta-minta... Tetapi orang miskin sejati adalah orang yang tidak memiliki kecukupan, namun ia malu dan tidak meminta-minta kepada manusia.', 'book' => 'Bukhari, Muslim', 'number' => '1479', 'source' => 'HR. Bukhari no. 1479 & Muslim'],
            ['arabic_text' => 'كُلُّ أُمَّتِي مُعَافًى إِلاَّ الْمُجَاهِرِينَ', 'translation' => 'Setiap umatku akan diampuni dosanya kecuali al-mujahirun (orang yang terang-terangan berbuat dosa tanpa rasa malu)...', 'book' => 'Bukhari, Muslim', 'number' => '6069, 2990', 'source' => 'HR. Bukhari no. 6069 & Muslim no. 2990'],
            ['arabic_text' => 'إِنَّ اللَّهَ حَيِيٌّ كَرِيمٌ يَسْتَحْيِي إِذَا رَفَعَ الرَّجُلُ إِلَيْهِ يَدَيْهِ أَنْ يَرُدَّهُمَا صِفْرًا خَائِبَتَيْنِ', 'translation' => 'Sesungguhnya Allah Maha Pemalu lagi Mahamulia. Dia malu jika seorang hamba mengangkat kedua tangannya kepada-Nya, lalu Dia mengembalikannya dalam keadaan kosong/kecewa.', 'book' => 'Tirmidzi, Abu Dawud', 'number' => '3556', 'source' => 'HR. Tirmidzi no. 3556 & Abu Dawud'],
            ['arabic_text' => 'أَرْبَعٌ مِنْ سُنَنِ الْمُرْسَلِينَ: الْحَيَاءُ، وَالتَّعَطُّرُ، وَالسِّوَاكُ، وَالنِّكَاحُ', 'translation' => 'Empat hal yang termasuk sunnah para Rasul: memiliki rasa malu, memakai minyak wangi, bersiwak, dan menikah.', 'book' => 'Tirmidzi', 'number' => '1080', 'source' => 'HR. Tirmidzi no. 1080'],
            ['arabic_text' => 'إِيَّاكُمْ وَالْعُرْيَ، فَإِنَّ مَعَكُمْ مَنْ لاَ يُفَارِقُكُمْ إِلاَّ عِنْدَ الْغَائِطِ وَحِينَ يُفْضِي الرَّجُلُ إِلَى أَهْلِهِ، فَاسْتَحْيُوهُمْ وَأَكْرِمُوهُمْ', 'translation' => 'Jauhilah oleh kalian bertelanjang (tanpa busana), karena bersama kalian ada (malaikat) yang tidak pernah berpisah dengan kalian kecuali saat buang air dan ketika bersetubuh. Maka malulah kepada mereka dan hormatilah mereka.', 'book' => 'Tirmidzi', 'number' => '2800', 'source' => 'HR. Tirmidzi no. 2800'],
            ['arabic_text' => 'لاَ يَنْظُرُ الرَّجُلُ إِلَى عَوْرَةِ الرَّجُلِ وَلاَ الْمَرْأَةُ إِلَى عَوْرَةِ الْمَرْأَةِ', 'translation' => 'Janganlah seorang laki-laki melihat aurat laki-laki lain, dan jangan pula seorang wanita melihat aurat wanita lain.', 'book' => 'Muslim', 'number' => '338', 'source' => 'HR. Muslim no. 338'],
            ['arabic_text' => 'الْبِرُّ حُسْنُ الْخُلُقِ، وَالإِثْمُ مَا حَاكَ فِي صَدْرِكَ وَكَرِهْتَ أَنْ يَطَّلِعَ عَلَيْهِ النَّاسُ', 'translation' => 'Kebaikan itu adalah akhlak yang baik, sedangkan dosa adalah apa yang meragukan/mengganjal dalam dadamu dan engkau benci (malu) jika hal itu diketahui oleh manusia.', 'book' => 'Muslim', 'number' => '2553', 'source' => 'HR. Muslim no. 2553'],
        ];

        foreach ($quranVerses as $verse) {
            $this->db->table('quran_verses')->insert([
                'surah'       => $verse['surah'],
                'ayat_number' => $verse['ayat_number'],
                'arabic_text' => $verse['arabic_text'],
                'translation' => $verse['translation'],
                'source'      => "Al-Qur'an",
                'tags'        => $verse['tags'],
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ]);
        }

        foreach ($hadiths as $hadith) {
            $this->db->table('hadiths')->insert([
                'arabic_text' => $hadith['arabic_text'],
                'translation' => $hadith['translation'],
                'book'        => $hadith['book'],
                'number'      => $hadith['number'],
                'source'      => $hadith['source'],
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ]);
        }

        echo 'Seeded ' . count($quranVerses) . ' quran verses and ' . count($hadiths) . ' hadiths (malu).' . PHP_EOL;
    }
}
