<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ContentBahagiaSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $quranVerses = [
            ['surah' => 10, 'ayat_number' => 58, 'arabic_text' => 'قُلْ بِفَضْلِ اللَّهِ وَبِرَحْمَتِهِ فَبِذَٰلِكَ فَلْيَفْرَحُوا هُوَ خَيْرٌ مِمَّا يَجْمَعُونَ', 'translation' => 'Katakanlah (Muhammad): \'Dengan karunia Allah dan rahmat-Nya, hendaklah dengan itu mereka bergembira. Itu lebih baik daripada apa yang mereka kumpulkan.\'', 'tags' => 'bahagia, rahmat Allah, karunia'],
            ['surah' => 3, 'ayat_number' => 170, 'arabic_text' => 'فَرِحِينَ بِمَا آتَاهُمُ اللَّهُ مِنْ فَضْلِهِ وَيَسْتَبْشِرُونَ بِالَّذِينَ لَمْ يَلْحَقُوا بِهِمْ مِنْ خَلْفِهِمْ', 'translation' => 'Mereka bergembira dengan karunia yang diberikan Allah kepada mereka, dan bergirang hati terhadap orang-orang yang masih tinggal di belakang yang belum menyusul mereka...', 'tags' => 'bahagia, kegembiraan, karunia Allah'],
            ['surah' => 30, 'ayat_number' => 4, 'arabic_text' => 'وَيَوْمَئِذٍ يَفْرَحُ الْمُؤْمِنُونَ بِنَصْرِ اللَّهِ', 'translation' => '...Dan pada hari itu bergembiralah orang-orang yang beriman karena pertolongan Allah.', 'tags' => 'bahagia, pertolongan Allah, kemenangan'],
            ['surah' => 83, 'ayat_number' => 22, 'arabic_text' => 'إِنَّ الْأَبْرَارَ لَفِي نَعِيمٍ', 'translation' => 'Sesungguhnya orang-orang yang berbakti benar-benar berada dalam (surga yang penuh) kenikmatan.', 'tags' => 'bahagia, kenikmatan, surga'],
            ['surah' => 83, 'ayat_number' => 24, 'arabic_text' => 'تَعْرِفُ فِي وُجُوهِهِمْ نَضْرَةَ النَّعِيمِ', 'translation' => 'Engkau dapat mengenali pada wajah mereka kesenangan hidup yang penuh kenikmatan.', 'tags' => 'bahagia, wajah berseri, kenikmatan'],
            ['surah' => 88, 'ayat_number' => 8, 'arabic_text' => 'وُجُوهٌ يَوْمَئِذٍ نَاعِمَةٌ', 'translation' => 'Pada hari itu banyak wajah yang berseri-seri,', 'tags' => 'bahagia, wajah berseri, kebahagiaan akhirat'],
            ['surah' => 88, 'ayat_number' => 9, 'arabic_text' => 'لِسَعْيِهَا رَاضِيَةٌ', 'translation' => 'merasa puas/bahagia karena usahanya,', 'tags' => 'bahagia, kepuasan, balasan amal'],
            ['surah' => 75, 'ayat_number' => 22, 'arabic_text' => 'وُجُوهٌ يَوْمَئِذٍ نَاضِرَةٌ', 'translation' => 'Wajah-wajah (orang mukmin) pada hari itu berseri-seri,', 'tags' => 'bahagia, kebahagiaan, kenikmatan melihat Allah'],
            ['surah' => 75, 'ayat_number' => 23, 'arabic_text' => 'إِلَىٰ رَبِّهَا نَاظِرَةٌ', 'translation' => 'memandang kepada Tuhannya.', 'tags' => 'bahagia, nikmat tertinggi, melihat Allah'],
            ['surah' => 13, 'ayat_number' => 29, 'arabic_text' => 'الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ طُوبَىٰ لَهُمْ وَحُسْنُ مَآبٍ', 'translation' => 'Orang-orang yang beriman dan mengerjakan kebajikan, kebahagiaan (kebajikan/kebahagiaan abadi) bagi mereka dan tempat kembali yang baik.', 'tags' => 'bahagia, kebahagiaan abadi, amal saleh'],
            ['surah' => 11, 'ayat_number' => 105, 'arabic_text' => 'يَوْمَ يَأْتِ لَا تَكَلَّمُ نَفْسٌ إِلَّا بِإِذْنِهِ ۚ فَمِنْهُمْ شَقِيٌّ وَسَعِيدٌ', 'translation' => 'Ketika hari itu datang, tidak seorang pun yang berbicara melainkan dengan izin-Nya; maka di antara mereka ada yang celaka dan ada yang bahagia.', 'tags' => 'bahagia, sa\'id, akhirat'],
            ['surah' => 11, 'ayat_number' => 108, 'arabic_text' => 'وَأَمَّا الَّذِينَ سُعِدُوا فَفِي الْجَنَّةِ خَالِدِينَ فِيهَا', 'translation' => 'Adapun orang-orang yang berbahagia, maka tempatnya di dalam surga; mereka kekal di dalamnya...', 'tags' => 'bahagia, surga, kekal'],
            ['surah' => 94, 'ayat_number' => 1, 'arabic_text' => 'أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ', 'translation' => 'Bukankah Kami telah melapangkan dadamu (Muhammad)?', 'tags' => 'bahagia, lapang dada, ketenangan'],
            ['surah' => 93, 'ayat_number' => 5, 'arabic_text' => 'وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ', 'translation' => 'Dan sungguh, kelak Tuhanmu pasti memberikan karunia-Nya kepadamu, sehingga engkau menjadi puas (bahagia).', 'tags' => 'bahagia, kepuasan, janji Allah'],
            ['surah' => 13, 'ayat_number' => 28, 'arabic_text' => 'الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُمْ بِذِكْرِ اللَّهِ ۗ أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ', 'translation' => '(yaitu) orang-orang yang beriman dan hati mereka menjadi tenteram dengan mengingat Allah. Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram (bahagia).', 'tags' => 'bahagia, ketenangan hati, zikir'],
            ['surah' => 16, 'ayat_number' => 97, 'arabic_text' => 'مَنْ عَمِلَ صَالِحًا مِنْ ذَكَرٍ أَوْ أُنْثَىٰ وَهُوَ مُؤْمِنٌ فَلَنُحْيِيَنَّهُ حَيَاةً طَيِّبَةً', 'translation' => 'Barangsiapa mengerjakan kebajikan, baik laki-laki maupun perempuan dalam keadaan beriman, maka sungguh akan Kami berikan kepadanya kehidupan yang baik (bahagia)...', 'tags' => 'bahagia, kehidupan yang baik, amal saleh'],
            ['surah' => 20, 'ayat_number' => 123, 'arabic_text' => 'فَمَنِ اتَّبَعَ هُدَايَ فَلَا يَضِلُّ وَلَا يَشْقَىٰ', 'translation' => '...Lalu barangsiapa mengikuti petunjuk-Ku, dia tidak akan sesat dan tidak akan celaka (akan berbahagia).', 'tags' => 'bahagia, petunjuk Allah, jauh dari celaka'],
            ['surah' => 28, 'ayat_number' => 13, 'arabic_text' => 'فَرَدَدْنَاهُ إِلَىٰ أُمِّهِ كَيْ تَقَرَّ عَيْنُهَا وَلَا تَحْزَنَ', 'translation' => 'Maka Kami kembalikan dia (Musa) kepada ibunya, agar senang/bahagia hatinya dan tidak bersedih...', 'tags' => 'bahagia, penenang hati, kebahagiaan keluarga'],
            ['surah' => 19, 'ayat_number' => 96, 'arabic_text' => 'إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ سَيَجْعَلُ لَهُمُ الرَّحْمَٰنُ وُدًّا', 'translation' => 'Sungguh, orang-orang yang beriman dan beramal saleh, kelak Allah Yang Maha Pengasih akan menanamkan rasa kasih sayang (kebahagiaan) dalam hati mereka.', 'tags' => 'bahagia, kasih sayang, cinta Allah'],
            ['surah' => 48, 'ayat_number' => 4, 'arabic_text' => 'هُوَ الَّذِي أَنْزَلَ السَّكِينَةَ فِي قُلُوبِ الْمُؤْمِنِينَ لِيَزْدَادُوا إِيمَانًا مَعَ إِيمَانِهِمْ', 'translation' => 'Dialah yang telah menurunkan ketenangan (sakinah) ke dalam hati orang-orang mukmin...', 'tags' => 'bahagia, ketenangan, sakinah'],
            ['surah' => 41, 'ayat_number' => 30, 'arabic_text' => 'أَلَّا تَخَافُوا وَلَا تَحْزَنُوا وَأَبْشِرُوا بِالْجَنَّةِ الَّتِي كُنْتُمْ تُوعَدُونَ', 'translation' => '...\'Janganlah kamu takut dan janganlah merasa sedih; dan bergembiralah dengan surga yang telah dijanjikan kepadamu.\'', 'tags' => 'bahagia, kabar gembira, surga'],
            ['surah' => 36, 'ayat_number' => 55, 'arabic_text' => 'إِنَّ أَصْحَابَ الْجَنَّةِ الْيَوْمَ فِي شُغُلٍ فَاكِهُونَ', 'translation' => 'Sesungguhnya penghuni surga pada hari itu bersenang-senang dalam kesibukan (yang membahagiakan).', 'tags' => 'bahagia, kenikmatan surga, kegembiraan'],
            ['surah' => 83, 'ayat_number' => 34, 'arabic_text' => 'فَالْيَوْمَ الَّذِينَ آمَنُوا مِنَ الْكُفَّارِ يَضْحَكُونَ', 'translation' => 'Maka pada hari ini, orang-orang yang beriman tertawa (bahagia) atas orang-orang kafir.', 'tags' => 'bahagia, kebahagiaan hakiki, kemenangan'],
            ['surah' => 21, 'ayat_number' => 103, 'arabic_text' => 'لَا يَحْزُنُهُمُ الْفَزَعُ الْأَكْبَرُ وَتَتَلَقَّاهُمُ الْمَلَائِكَةُ هَٰذَا يَوْمُكُمُ الَّذِي كُنْتُمْ تُوعَدُونَ', 'translation' => 'Mereka tidak didegupkan oleh kejutan yang dahsyat (hari kiamat), dan mereka disambut oleh para malaikat: \'Inilah harimu yang telah dijanjikan kepadamu.\'', 'tags' => 'bahagia, rasa aman, janji Allah'],
            ['surah' => 52, 'ayat_number' => 18, 'arabic_text' => 'فَاكِهِينَ بِمَا آتَاهُمْ رَبُّهُمْ وَوَقَاهُمْ رَبُّهُمْ عَذَابَ الْجَحِيمِ', 'translation' => 'Mereka bersenang-senang (bahagia) dengan apa yang diberikan Tuhan kepada mereka; dan Tuhan memelihara mereka dari azab neraka.', 'tags' => 'bahagia, kegembiraan surga, perlindungan'],
            ['surah' => 76, 'ayat_number' => 11, 'arabic_text' => 'فَوَقَاهُمُ اللَّهُ شَرَّ ذَٰلِكَ الْيَوْمِ وَلَقَّاهُمْ نَضْرَةً وَسُرُورًا', 'translation' => 'Maka Allah melindungi mereka dari kesusahan hari itu, dan memberikan kepada mereka kecerahan (wajah) dan kegembiraan hati.', 'tags' => 'bahagia, kegembiraan hati, kecerahan'],
            ['surah' => 84, 'ayat_number' => 9, 'arabic_text' => 'وَيَنْقَلِبُ إِلَىٰ أَهْلِهِ مَسْرُورًا', 'translation' => 'dan dia akan kembali kepada keluarganya (yang sama-sama beriman) dengan gembira (bahagia).', 'tags' => 'bahagia, kegembiraan, hisab mudah'],
            ['surah' => 27, 'ayat_number' => 19, 'arabic_text' => 'فَتَبَسَّمَ ضَاحِكًا مِنْ قَوْلِهَا', 'translation' => 'Maka dia (Sulaiman) tersenyum tertawa karena (mendengar) perkataan semut itu...', 'tags' => 'bahagia, senyuman, Nabi Sulaiman'],
            ['surah' => 10, 'ayat_number' => 62, 'arabic_text' => 'أَلَا إِنَّ أَوْلِيَاءَ اللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ', 'translation' => 'Ingatlah, sesungguhnya wali-wali Allah itu tidak ada kekhawatiran terhadap mereka dan tidak (pula) mereka bersedih hati.', 'tags' => 'bahagia, kedamaian jiwa, wali Allah'],
            ['surah' => 10, 'ayat_number' => 63, 'arabic_text' => 'الَّذِينَ آمَنُوا وَكَانُوا يَتَّقُونَ', 'translation' => '(Yaitu) orang-orang yang beriman dan selalu bertakwa.', 'tags' => 'bahagia, iman dan takwa, kunci bahagia'],
            ['surah' => 10, 'ayat_number' => 64, 'arabic_text' => 'لَهُمُ الْبُشْرَىٰ فِي الْحَيَاةِ الدُّنْيَا وَفِي الْآخِرَةِ', 'translation' => 'Bagi mereka berita gembira di dalam kehidupan dunia dan di akhirat...', 'tags' => 'bahagia, kabar gembira, dunia akhirat'],
            ['surah' => 25, 'ayat_number' => 74, 'arabic_text' => 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ', 'translation' => 'Ya Tuhan kami, anugerahkanlah kepada kami pasangan kami dan keturunan kami sebagai penyenang hati (kebahagiaan)...', 'tags' => 'bahagia, penyenang hati, keluarga bahagia'],
            ['surah' => 30, 'ayat_number' => 21, 'arabic_text' => 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُمْ مِنْ أَنْفُسِكُمْ أَزْوَاجًا لِتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُمْ مَوَدَّةً وَرَحْمَةً', 'translation' => 'Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu merasa tenteram/bahagia kepadanya...', 'tags' => 'bahagia, ketenteraman, pernikahan'],
            ['surah' => 55, 'ayat_number' => 60, 'arabic_text' => 'هَلْ جَزَاءُ الْإِحْسَانِ إِلَّا الْإِحْسَانُ', 'translation' => 'Tidak ada balasan untuk kebaikan selain kebaikan (yang membahagiakan) pula.', 'tags' => 'bahagia, balasan ihsan, kebaikan'],
            ['surah' => 65, 'ayat_number' => 7, 'arabic_text' => 'سَيَجْعَلُ اللَّهُ بَعْدَ عُسْرٍ يُسْرًا', 'translation' => 'Allah kelak akan memberikan kelapangan (kebahagiaan) setelah kesempitan.', 'tags' => 'bahagia, kelapangan, kemudahan'],
        ];

        $hadiths = [
            ['arabic_text' => 'عَجَبًا لأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ... إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ', 'translation' => 'Sungguh menakjubkan urusan seorang mukmin, seluruh urusannya adalah baik baginya. Jika ia mendapatkan kesenangan/kebahagiaan ia bersyukur, maka itu baik baginya...', 'book' => 'Muslim', 'number' => '2999', 'source' => 'HR. Muslim no. 2999'],
            ['arabic_text' => 'مَنْ أَصْبَحَ مِنْكُمْ آمِنًا فِي سِرْبِهِ، مُعَافًى فِي جَسَدِهِ، عِنْدَهُ قُوتُ يَوْمِهِ، فَكَأَنَّمَا حِيزَتْ لَهُ الدُّنْيَا', 'translation' => 'Barangsiapa di antara kalian merasa aman di tempat tinggalnya, sehat badannya, dan memiliki makanan untuk harinya, maka seolah-olah dunia telah dikumpulkan untuknya (puncak bahagia).', 'book' => 'Tirmidzi', 'number' => '2346', 'source' => 'HR. Tirmidzi no. 2346'],
            ['arabic_text' => 'قَدْ أَفْلَحَ مَنْ أَسْلَمَ وَرُزِقَ كَفَافًا وَقَنَّعَهُ اللَّهُ بِمَا آتَاهُ', 'translation' => 'Sungguh beruntung (bahagia) orang yang telah berserah diri (masuk Islam), diberi rezeki yang cukup, dan dijadikan merasa cukup (qana\'ah) oleh Allah atas apa yang diberikan kepadanya.', 'book' => 'Muslim', 'number' => '1054', 'source' => 'HR. Muslim no. 1054'],
            ['arabic_text' => 'لَيْسَ الْغِنَى عَنْ كَثْرَةِ الْعَرَضِ، وَلَكِنَّ الْغِنَى غِنَى النَّفْسِ', 'translation' => 'Kekayaan (kebahagiaan hakiki) itu bukanlah dengan banyaknya harta benda, melainkan kekayaan itu adalah kaya hati (rasa cukup).', 'book' => 'Bukhari, Muslim', 'number' => '6446, 1051', 'source' => 'HR. Bukhari no. 6446 & Muslim no. 1051'],
            ['arabic_text' => 'لِلصَّائِمِ فَرْحَتَانِ يَفْرَحُهُمَا: إِذَا أَفْطَرَ فَرِحَ، وَإِذَا لَقِيَ رَبَّهُ فَرِحَ بِصَوْمِهِ', 'translation' => 'Bagi orang yang berpuasa ada dua kegembiraan (kebahagiaan) yang dirasakannya: saat ia berbuka ia bergembira, dan saat ia bertemu Tuhannya ia bergembira karena pahala puasanya.', 'book' => 'Bukhari, Muslim', 'number' => '1904, 1151', 'source' => 'HR. Bukhari no. 1904 & Muslim no. 1151'],
            ['arabic_text' => 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ', 'translation' => 'Senyummu di hadapan saudaramu adalah sedekah bagimu.', 'book' => 'Tirmidzi', 'number' => '1956', 'source' => 'HR. Tirmidzi no. 1956'],
            ['arabic_text' => 'أَفْضَلُ الأَعْمَالِ إِدْخَالُ السُّرُورِ عَلَى الْمُؤْمِنِ', 'translation' => 'Amalan yang paling utama adalah memasukkan rasa gembira/bahagia ke dalam hati seorang mukmin.', 'book' => 'Thabrani', 'number' => null, 'source' => 'HR. Thabrani (Al-Mu\'jam al-Awsat) & Albani'],
            ['arabic_text' => 'أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ سُرُورٌ تُدْخِلُهُ عَلَى مُسْلِمٍ', 'translation' => 'Amalan yang paling dicintai Allah adalah kegembiraan yang engkau masukkan ke dalam diri seorang muslim...', 'book' => 'Ibnu Abi ad-Dunya', 'number' => null, 'source' => 'HR. Ibn Abi ad-Dunya & As-Silsilah as-Sahihah no. 906'],
            ['arabic_text' => 'مَنْ كَانَتِ الآخِرَةُ هَمَّهُ جَعَلَ اللَّهُ غِنَاهُ فِي قَلْبِهِ وَجَمَعَ لَهُ شَمْلَهُ وَأَتَتْهُ الدُّنْيَا وَهِيَ رَاغِمَةٌ', 'translation' => 'Barangsiapa yang niat utamanya adalah akhirat, niscaya Allah akan menjadikan kekayaan/kebahagiaan dalam hatinya, menyatukan urusannya, dan dunia akan mendatanginya dalam keadaan tunduk.', 'book' => 'Tirmidzi', 'number' => '2465', 'source' => 'HR. Tirmidzi no. 2465'],
            ['arabic_text' => 'أَرْبَعٌ مِنَ السَّعَادَةِ: الْمَرْأَةُ الصَّالِحَةُ، وَالْمَسْكَنُ الْوَاسِعُ، وَالْجَارُ الصَّالِحُ، وَالْمَرْكَبُ الْهَنِيءُ', 'translation' => 'Empat hal yang termasuk kebahagiaan: istri/pasangan yang saleh, tempat tinggal yang luas, tetangga yang baik, dan kendaraan yang nyaman.', 'book' => 'Ibnu Hibban', 'number' => '4032', 'source' => 'HR. Ibn Hibban no. 4032 & Al-Albani'],
            ['arabic_text' => 'ذَاقَ طَعْمَ الإِيمَانِ مَنْ رَضِيَ بِاللَّهِ رَبًّا وَبِالإِسْلاَمِ دِينًا وَبِمُحَمَّدٍ رَسُولاً', 'translation' => 'Akan merasakan kemanisan (kebahagiaan) iman: orang yang ridha Allah sebagai Rabb-nya, Islam sebagai agamanya, dan Muhammad sebagai Rasul-Nya.', 'book' => 'Muslim', 'number' => '34', 'source' => 'HR. Muslim no. 34'],
            ['arabic_text' => 'ثَلاَثٌ مَنْ كُنَّ فِيهِ وَجَدَ حَلاَوَةَ الإِيمَانِ: أَنْ يَكُونَ اللَّهُ وَرَسُولُهُ أَحَبَّ إِلَيْهِ مِمَّا سِوَاهُمَا...', 'translation' => 'Tiga hal yang apabila ada pada diri seseorang, ia akan merasakan manisnya (kebahagiaan) iman: Allah dan Rasul-Nya lebih ia cintai dari selain keduanya...', 'book' => 'Bukhari, Muslim', 'number' => '16, 43', 'source' => 'HR. Bukhari no. 16 & Muslim no. 43'],
            ['arabic_text' => 'وَجُعِلَتْ قُرَّةُ عَيْنِي فِي الصَّلاَةِ', 'translation' => '...Dan dijadikan puncak kebahagiaan/kesenanganku berada di dalam salat.', 'book' => 'An-Nasa\'i', 'number' => '3940', 'source' => 'HR. An-Nasa\'i no. 3940'],
            ['arabic_text' => 'أَرِحْنَا بِهَا يَا بِلاَلُ', 'translation' => 'Istirahatkanlah kami (buatlah kami bahagia/tenang) dengan salat, wahai Bilal!', 'book' => 'Abu Dawud', 'number' => '4985', 'source' => 'HR. Abu Dawud no. 4985'],
            ['arabic_text' => 'اللَّهُمَّ إِنِّي أَسْأَلُكَ النَّعِيمَ الَّذِي لاَ يَحُولُ وَلاَ يَزُولُ', 'translation' => 'Ya Allah, sesungguhnya aku memohon kepada-Mu kenikmatan (kebahagiaan) yang tidak akan berubah dan tidak akan sirna.', 'book' => 'An-Nasa\'i, Ahmad', 'number' => null, 'source' => 'HR. An-Nasa\'i (Al-Sunan al-Kubra) & Ahmad'],
        ];

        foreach ($quranVerses as $v) {
            $this->db->table('quran_verses')->insert(['surah' => $v['surah'], 'ayat_number' => $v['ayat_number'], 'arabic_text' => $v['arabic_text'], 'translation' => $v['translation'], 'source' => "Al-Qur'an", 'tags' => $v['tags'], 'status' => 'approved', 'created_at' => $now, 'updated_at' => $now]);
        }
        foreach ($hadiths as $h) {
            $this->db->table('hadiths')->insert(['arabic_text' => $h['arabic_text'], 'translation' => $h['translation'], 'book' => $h['book'], 'number' => $h['number'], 'source' => $h['source'], 'status' => 'approved', 'created_at' => $now, 'updated_at' => $now]);
        }

        echo 'Seeded ' . count($quranVerses) . ' quran verses and ' . count($hadiths) . ' hadiths (bahagia).' . PHP_EOL;
    }
}
