<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ContentSemangatSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $quranVerses = [
            ['surah' => 94, 'ayat_number' => 7, 'arabic_text' => 'فَإِذَا فَرَغْتَ فَانْصَبْ', 'translation' => 'Maka apabila engkau telah selesai (dari suatu urusan), tetaplah bekerja keras (untuk urusan yang lain).', 'tags' => 'semangat, kerja keras, produktivitas'],
            ['surah' => 94, 'ayat_number' => 8, 'arabic_text' => 'وَإِلَىٰ رَبِّكَ فَارْغَبْ', 'translation' => 'Dan hanya kepada Tuhanmulah engkau berharap.', 'tags' => 'semangat, harapan, niat'],
            ['surah' => 3, 'ayat_number' => 139, 'arabic_text' => 'وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنْتُمُ الْأَعْلَوْنَ إِنْ كُنْتُمْ مُؤْمِنِينَ', 'translation' => 'Janganlah kamu (merasa) lemah, dan jangan (pula) bersedih hati, padahal kamu pun orang-orang yang paling tinggi (derajatnya), jika kamu orang-orang yang beriman.', 'tags' => 'semangat, pantang menyerah, optimisme'],
            ['surah' => 29, 'ayat_number' => 69, 'arabic_text' => 'وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا ۚ وَإِنَّ اللَّهَ لَمَعَ الْمُحْسِنِينَ', 'translation' => 'Dan orang-orang yang berjihad (bersungguh-sungguh) untuk (mencari keridhaan) Kami, sungguh Kami akan tunjukkan kepada mereka jalan-jalan Kami...', 'tags' => 'semangat, kesungguhan, petunjuk'],
            ['surah' => 2, 'ayat_number' => 148, 'arabic_text' => 'فَاسْتَبِقُوا الْخَيْرَاتِ', 'translation' => 'Maka berlomba-lombalah kamu dalam berbuat kebaikan.', 'tags' => 'semangat, berlomba dalam kebaikan, motivasi'],
            ['surah' => 5, 'ayat_number' => 48, 'arabic_text' => 'فَاسْتَبِقُوا الْخَيْرَاتِ ۚ إِلَى اللَّهِ مَرْجِعُكُمْ جَمِيعًا', 'translation' => '...Maka berlomba-lombalah berbuat kebaikan. Hanya kepada Allah kamu semua kembali...', 'tags' => 'semangat, kompetisi positif, kebaikan'],
            ['surah' => 83, 'ayat_number' => 26, 'arabic_text' => 'وَفِي ذَٰلِكَ فَلْيَتَنَافَسِ الْمُتَنَافِسُونَ', 'translation' => '...Dan untuk yang demikian itu hendaknya orang berlomba-lomba.', 'tags' => 'semangat, amalan akhirat, motivasi tinggi'],
            ['surah' => 57, 'ayat_number' => 21, 'arabic_text' => 'سَابِقُوا إِلَىٰ مَغْفِرَةٍ مِنْ رَبِّكُمْ وَجَنَّةٍ عَرْضُهَا كَعَرْضِ السَّمَاءِ وَالْأَرْضِ', 'translation' => 'Berlomba-lombalah kamu untuk mendapatkan ampunan dari Tuhanmu dan surga yang luasnya seluas langit dan bumi...', 'tags' => 'semangat, pengampunan, perjuangan surga'],
            ['surah' => 3, 'ayat_number' => 133, 'arabic_text' => 'وَسَارِعُوا إِلَىٰ مَغْفِرَةٍ مِنْ رَبِّكُمْ وَجَنَّةٍ عَرْضُهَا السَّمَاوَاتُ وَالْأَرْضُ', 'translation' => 'Dan bersegeralah kamu mencari ampunan dari Tuhanmu dan mendapatkan surga yang luasnya seluas langit dan bumi...', 'tags' => 'semangat, bersegera, kebaikan'],
            ['surah' => 13, 'ayat_number' => 11, 'arabic_text' => 'إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنْفُسِهِمْ', 'translation' => '...Sesungguhnya Allah tidak akan mengubah keadaan suatu kaum sebelum mereka mengubah keadaan diri mereka sendiri...', 'tags' => 'semangat, perubahan, ikhtiar'],
            ['surah' => 53, 'ayat_number' => 39, 'arabic_text' => 'وَأَنْ لَيْسَ لِلْإِنْسَانِ إِلَّا مَا سَعَىٰ', 'translation' => 'Dan bahwa manusia hanya memperoleh apa yang telah diusahakannya.', 'tags' => 'semangat, usaha, etos kerja'],
            ['surah' => 53, 'ayat_number' => 40, 'arabic_text' => 'وَأَنَّ سَعْيَهُ سَوْفَ يُرَىٰ', 'translation' => 'Dan bahwa usahanya itu kelak akan diperlihatkan (kepadanya).', 'tags' => 'semangat, hasil kerja, apresiasi'],
            ['surah' => 9, 'ayat_number' => 105, 'arabic_text' => 'وَقُلِ اعْمَلُوا فَسَيَرَى اللَّهُ عَمَلَكُمْ وَرَسُولُهُ وَالْمُؤْمِنُونَ', 'translation' => 'Dan katakanlah: \'Bekerjalah kamu, maka Allah akan melihat pekerjaanmu, begitu juga Rasul-Nya dan orang-orang mukmin...\'', 'tags' => 'semangat, etos kerja, amal nyata'],
            ['surah' => 67, 'ayat_number' => 15, 'arabic_text' => 'هُوَ الَّذِي جَعَلَ لَكُمُ الْأَرْضَ ذَلُولًا فَامْشُوا فِي مَنَاكِبِهَا وَكُلُوا مِنْ رِزْقِهِ', 'translation' => 'Dialah yang menjadikan bumi untuk kamu yang mudah dijelajahi, maka jelajahilah di segala penjurunya dan makanlah sebagian dari rezeki-Nya...', 'tags' => 'semangat, mencari rezeki, ekplorasi'],
            ['surah' => 62, 'ayat_number' => 10, 'arabic_text' => 'فَإِذَا قُضِيَتِ الصَّلَاةُ فَانْتَشِرُوا فِي الْأَرْضِ وَابْتَغُوا مِنْ فَضْلِ اللَّهِ', 'translation' => 'Apabila salat telah dilaksanakan, maka bertebaranlah kamu di bumi; carilah karunia Allah...', 'tags' => 'semangat, etos kerja, keseimbangan hidup'],
            ['surah' => 3, 'ayat_number' => 159, 'arabic_text' => 'فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ ۚ إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ', 'translation' => '...Kemudian, apabila engkau telah membulatkan tekad, maka bertawakallah kepada Allah. Sungguh, Allah mencintai orang-orang yang bertawakal.', 'tags' => 'semangat, tekad bulat, tawakal'],
            ['surah' => 22, 'ayat_number' => 78, 'arabic_text' => 'وَجَاهِدُوا فِي اللَّهِ حَقَّ جِهَادِهِ', 'translation' => 'Dan berjihadlah (berjuanglah) kamu di jalan Allah dengan jihad yang sebenar-benarnya...', 'tags' => 'semangat, perjuangan, kesungguhan'],
            ['surah' => 9, 'ayat_number' => 41, 'arabic_text' => 'انْفِرُوا خِفَافًا وَثِقَالًا وَجَاهِدُوا بِأَمْوَالِكُمْ وَأَنْفُسِكُمْ فِي سَبِيلِ اللَّهِ', 'translation' => 'Berangkatlah kamu baik dalam keadaan merasa ringan maupun berat, dan berjihadlah dengan harta dan jiwamu di jalan Allah...', 'tags' => 'semangat, pengorbanan, penggerak diri'],
            ['surah' => 12, 'ayat_number' => 87, 'arabic_text' => 'وَلَا تَيْأَسُوا مِنْ رَوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِنْ رَوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ', 'translation' => '...dan jangan kamu berputus asa dari rahmat Allah. Sesungguhnya yang berputus asa dari rahmat Allah, hanyalah kaum yang kafir.', 'tags' => 'semangat, pantang putus asa, optimisme'],
            ['surah' => 39, 'ayat_number' => 53, 'arabic_text' => 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ', 'translation' => 'Katakanlah: \'Wahai hamba-hamba-Ku yang melampaui batas terhadap diri mereka sendiri, janganlah kamu berputus asa dari rahmat Allah...\'', 'tags' => 'semangat, harapan, kebangkitan'],
            ['surah' => 28, 'ayat_number' => 77, 'arabic_text' => 'وَابْتَغِ فِيمَا آتَاكَ اللَّهُ الدَّارَ الْآخِرَةَ ۖ وَلَا تَنْسَ نَصِيبَكَ مِنَ الدُّنْيَا', 'translation' => 'Dan carilah pada apa yang telah dianugerahkan Allah kepadamu (kebahagiaan) negeri akhirat, dan janganlah kamu melupakan bagianmu dari (kenikmatan) dunia...', 'tags' => 'semangat, keseimbangan, produktivitas'],
            ['surah' => 21, 'ayat_number' => 90, 'arabic_text' => 'إِنَّهُمْ كَانُوا يُسَارِعُونَ فِي الْخَيْرَاتِ وَيَدْعُونَنَا رَغَبًا وَرَهَبًا', 'translation' => '...Sungguh, mereka selalu bersegera dalam (mengerjakan) kebaikan-kebaikan, dan mereka berdoa kepada Kami dengan penuh harapan dan rasa takut...', 'tags' => 'semangat, bersegera, kebaikan'],
            ['surah' => 23, 'ayat_number' => 61, 'arabic_text' => 'أُولَٰئِكَ يُسَارِعُونَ فِي الْخَيْرَاتِ وَهُمْ لَهَا سَابِقُونَ', 'translation' => 'merekalah orang-orang yang bersegera dalam kebaikan-kebaikan, dan merekalah yang paling dahulu mendapatkannya.', 'tags' => 'semangat, pelopor kebaikan, kesungguhan'],
            ['surah' => 61, 'ayat_number' => 4, 'arabic_text' => 'إِنَّ اللَّهَ يُحِبُّ الَّذِينَ يُقَاتِلُونَ فِي سَبِيلِهِ صَفًّا كَأَنَّهُمْ بُنْيَانٌ مَرْصُوصٌ', 'translation' => 'Sesungguhnya Allah mencintai orang-orang yang berperang di jalan-Nya dalam barisan yang teratur seakan-akan mereka seperti suatu bangunan yang tersusun kokoh.', 'tags' => 'semangat, kekompakan, disiplin'],
            ['surah' => 47, 'ayat_number' => 35, 'arabic_text' => 'فَلَا تَهِنُوا وَتَدْعُوا إِلَى السَّلْمِ وَأَنْتُمُ الْأَعْلَوْنَ وَاللَّهُ مَعَكُمْ وَلَنْ يَتِرَكُمْ أَعْمَالَكُمْ', 'translation' => 'Maka janganlah kamu lemah dan mengajak damai karena takut, padahal kamulah yang unggul dan Allah pun bersamamu dan Dia tidak akan mengurangi pahala amal-amalmu.', 'tags' => 'semangat, keteguhan, motivasi'],
            ['surah' => 48, 'ayat_number' => 29, 'arabic_text' => 'مُحَمَّدٌ رَسُولُ اللَّهِ ۚ وَالَّذِينَ مَعَهُ أَشِدَّاءُ عَلَى الْكُفَّارِ رُحَمَاءُ بَيْنَهُمْ', 'translation' => 'Muhammad adalah utusan Allah dan orang-orang yang bersama dengan dia bersikap keras terhadap orang-orang kafir, tetapi berkasih sayang sesama mereka...', 'tags' => 'semangat, karakter tegas, ukhuwah'],
            ['surah' => 2, 'ayat_number' => 249, 'arabic_text' => 'كَمْ مِنْ فِئَةٍ قَلِيلَةٍ غَلَبَتْ فِئَةً كَثِيرَةً بِإِذْنِ اللَّهِ ۗ وَاللَّهُ مَعَ الصَّابِرِينَ', 'translation' => '...\'Berapa banyak terjadi golongan yang sedikit dapat mengalahkan golongan yang banyak dengan izin Allah? Dan Allah beserta orang-orang yang sabar.\'', 'tags' => 'semangat, optimisme, keyakinan'],
            ['surah' => 8, 'ayat_number' => 65, 'arabic_text' => 'يَا أَيُّهَا النَّبِيُّ حَرِّضِ الْمُؤْمِنِينَ عَلَى الْقِتَالِ', 'translation' => 'Wahai Nabi (Muhammad)! Kobarkanlah semangat orang-orang beriman untuk berperang...', 'tags' => 'semangat, pengobar semangat, motivasi pimpinan'],
            ['surah' => 4, 'ayat_number' => 84, 'arabic_text' => 'فَقَاتِلْ فِي سَبِيلِ اللَّهِ لَا تُكَلَّفُ إِلَّا نَفْسَكَ ۚ وَحَرِّضِ الْمُؤْمِنِينَ', 'translation' => 'Maka berperanglah engkau di jalan Allah, engkau tidak dibebani melainkan atas dirimu sendiri. Dan kobarkanlah semangat orang-orang beriman...', 'tags' => 'semangat, kepemimpinan, daya juang'],
            ['surah' => 3, 'ayat_number' => 146, 'arabic_text' => 'فَمَا وَهَنُوا لِمَا أَصَابَهُمْ فِي سَبِيلِ اللَّهِ وَمَا ضَعُفُوا وَمَا اسْتَكَانُوا ۗ وَاللَّهُ يُحِبُّ الصَّابِرِينَ', 'translation' => '...mereka tidak menjadi lemah karena bencana yang menimpa mereka di jalan Allah, tidak lesu dan tidak (pula) menyerah. Dan Allah menyukai orang-orang yang sabar.', 'tags' => 'semangat, daya tahan, tidak menyerah'],
            ['surah' => 3, 'ayat_number' => 200, 'arabic_text' => 'يَا أَيُّهَا الَّذِينَ آمَنُوا اصْبِرُوا وَصَابِرُوا وَرَابِطُوا وَاتَّقُوا اللَّهَ لَعَلَّكُمْ تُفْلِحُونَ', 'translation' => 'Wahai orang-orang yang beriman! Bersabarlah kamu dan tingkatkanlah kesabaranmu dan tetaplah bersiap-siap, dan bertakwalah kepada Allah agar kamu beruntung.', 'tags' => 'semangat, daya tahan, kesiapan'],
            ['surah' => 39, 'ayat_number' => 10, 'arabic_text' => 'إِنَّمَا يُوَفَّى الصَّابِرُونَ أَجْرَهُمْ بِغَيْرِ حِسَابٍ', 'translation' => '...Sesungguhnya hanya orang-orang yang bersabarlah yang disempurnakan pahala mereka tanpa batas.', 'tags' => 'semangat, kesabaran, balasan tanpa batas'],
            ['surah' => 93, 'ayat_number' => 4, 'arabic_text' => 'وَلَلْآخِرَةُ خَيْرٌ لَكَ مِنَ الْأُولَىٰ', 'translation' => 'Dan sungguh, yang kemudian itu lebih baik bagimu daripada yang permulaan.', 'tags' => 'semangat, visi masa depan, optimisme'],
            ['surah' => 11, 'ayat_number' => 112, 'arabic_text' => 'فَاسْتَقِمْ كَمَا أُمِرْتَ وَمَنْ تَابَ مَعَكَ', 'translation' => 'Maka tetaplah engkau (di jalan yang benar), sebagaimana diperintahkan kepadamu dan (juga) orang yang telah bertobat bersamamu...', 'tags' => 'semangat, istiqamah, keteguhan'],
            ['surah' => 41, 'ayat_number' => 30, 'arabic_text' => 'إِنَّ الَّذِينَ قَالُوا رَبُّنَا اللَّهُ ثُمَّ اسْتَقَامُوا تَتَنَزَّلُ عَلَيْهِمُ الْمَلَائِكَةُ أَلَّا تَخَافُوا وَلَا تَحْزَنُوا', 'translation' => 'Sesungguhnya orang-orang yang berkata \'Tuhan kami ialah Allah\' kemudian mereka meneguhkan pendirian mereka, maka malaikat akan turun kepada mereka...', 'tags' => 'semangat, konsistensi, kabar gembira'],
        ];

        $hadiths = [
            ['arabic_text' => 'الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ وَفِي كُلٍّ خَيْرٌ', 'translation' => 'Mukmin yang kuat lebih baik dan lebih dicintai Allah daripada mukmin yang lemah, meskipun pada masing-masing ada kebaikan...', 'book' => 'Muslim', 'number' => '2664', 'source' => 'HR. Muslim no. 2664'],
            ['arabic_text' => 'احْرِصْ عَلَى مَا يَنْفَعُكَ وَاسْتَعِنْ بِاللَّهِ وَلاَ تَعْجِزْ', 'translation' => 'Semangatlah terhadap apa yang bermanfaat bagimu, mohonlah pertolongan kepada Allah, dan janganlah merasa lemah/patah semangat.', 'book' => 'Muslim', 'number' => '2664', 'source' => 'HR. Muslim no. 2664'],
            ['arabic_text' => 'إِنْ قَامَتِ السَّاعَةُ وَبِيَدِ أَحَدِكُمْ فَصِيلَةٌ فَإِنِ اسْتَطَاعَ أَنْ لاَ تَقُومَ حَتَّى يَغْرِسَهَا فَلْيَفْعَلْ', 'translation' => 'Jika hari kiamat telah tiba sedang di tangan salah seorang di antara kalian ada bibit pohon, maka jika ia mampu menanamnya sebelum kiamat terjadi, hendaklah ia menanamnya.', 'book' => 'Ahmad', 'number' => '12981', 'source' => 'HR. Ahmad no. 12981 & Al-Bukhari (Al-Adab al-Mufrad)'],
            ['arabic_text' => 'إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ', 'translation' => 'Sesungguhnya Allah menyukai jika salah seorang di antara kalian melakukan suatu pekerjaan, ia melakukannya secara itqan (sungguh-sungguh/profesional).', 'book' => 'Thabrani, Baihaqi', 'number' => '897', 'source' => 'HR. Thabrani no. 897 & Baihaqi'],
            ['arabic_text' => 'أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أدْوَمُهَا وَإِنْ قَلَّ', 'translation' => 'Amalan yang paling dicintai oleh Allah adalah amalan yang berkesinambungan (konsisten) meskipun sedikit.', 'book' => 'Bukhari, Muslim', 'number' => '6465, 783', 'source' => 'HR. Bukhari no. 6465 & Muslim no. 783'],
            ['arabic_text' => 'مَا أَكَلَ أَحَدٌ طَعَامًا قَطُّ خَيْرًا مِنْ أَنْ يَأْكُلَ مِنْ عَمَلِ يَدِهِ', 'translation' => 'Tidak ada seorang pun yang memakan makanan yang lebih baik daripada makan dari hasil kerja tangannya sendiri.', 'book' => 'Bukhari', 'number' => '2072', 'source' => 'HR. Bukhari no. 2072'],
            ['arabic_text' => 'لَأَنْ يَأْخُذَ أَحَدُكُمْ حَبْلَهُ فَيَأْتِيَ بِحُزْمَةِ حَطَبٍ عَلَى ظَهْرِهِ فَيَبِيعَهَا... خَيْرٌ لَهُ مِنْ أَنْ يَسْأَلَ النَّاسَ', 'translation' => 'Sungguh, jika salah seorang di antara kalian mengambil talinya lalu membawa seikat kayu bakar di atas punggungnya kemudian menjualnya... itu lebih baik baginya daripada meminta-minta kepada orang lain...', 'book' => 'Bukhari, Muslim', 'number' => '1471', 'source' => 'HR. Bukhari no. 1471 & Muslim'],
            ['arabic_text' => 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ', 'translation' => 'Ya Allah, aku berlindung kepada-Mu dari kelemahan dan kemalasan.', 'book' => 'Bukhari', 'number' => '6369', 'source' => 'HR. Bukhari no. 6369'],
            ['arabic_text' => 'بَارِكْ لأُمَّتِي فِي بُكُورِهَا', 'translation' => 'Ya Allah, berkahilah umatku pada waktu pagi hari mereka (saat memulai aktivitas dengan semangat).', 'book' => 'Abu Dawud, Tirmidzi', 'number' => '2606', 'source' => 'HR. Abu Dawud no. 2606 & Tirmidzi'],
            ['arabic_text' => 'يَسِّرُوا وَلاَ تُعَسِّرُوا، وَبَشِّرُوا وَلاَ تُنَفِّرُوا', 'translation' => 'Permudahlah dan jangan kamu persulit, berilah kabar gembira (bangkitkan semangat) dan jangan buat mereka lari/putus asa.', 'book' => 'Bukhari, Muslim', 'number' => '69, 1734', 'source' => 'HR. Bukhari no. 69 & Muslim no. 1734'],
            ['arabic_text' => 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ', 'translation' => 'Barangsiapa menempuh suatu jalan untuk mencari ilmu, maka Allah akan memudahkan jalannya menuju surga.', 'book' => 'Muslim', 'number' => '2699', 'source' => 'HR. Muslim no. 2699'],
            ['arabic_text' => 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ', 'translation' => 'Menuntut ilmu itu wajib bagi setiap muslim.', 'book' => 'Ibnu Majah', 'number' => '224', 'source' => 'HR. Ibn Majah no. 224'],
            ['arabic_text' => 'الْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى', 'translation' => 'Tangan yang di atas (memberi) lebih baik daripada tangan yang di bawah (menerima).', 'book' => 'Bukhari, Muslim', 'number' => '1429, 1033', 'source' => 'HR. Bukhari no. 1429 & Muslim no. 1033'],
            ['arabic_text' => 'سَدِّدُوا وَقَارِبُوا وَأَبْشِرُوا', 'translation' => 'Berlakulah lurus, mendekatlah (kepada kebenaran), dan bergembiralah (peliharalah semangatmu).', 'book' => 'Bukhari, Muslim', 'number' => '6467, 2818', 'source' => 'HR. Bukhari no. 6467 & Muslim no. 2818'],
            ['arabic_text' => 'إِنَّ لِكُلِّ عَمَلٍ شِرَّةً وَلِكُلِّ شِرَّةٍ فَتْرَةً فَمَنْ كَانَتْ فَتْرَتُهُ إِلَى سُنَّتِي فَقَدِ اهْتَدَى', 'translation' => 'Sesungguhnya setiap amalan memiliki masa semangat (puncak pendorong), dan setiap masa semangat memiliki titik jenuh. Barangsiapa yang saat jenuhnya tetap kembali pada sunnahku, maka sungguh ia telah mendapat petunjuk.', 'book' => 'Ahmad, Ibnu Hibban', 'number' => '6725', 'source' => 'HR. Ahmad no. 6725 & Ibn Hibban'],
        ];

        foreach ($quranVerses as $v) {
            $this->db->table('quran_verses')->insert(['surah' => $v['surah'], 'ayat_number' => $v['ayat_number'], 'arabic_text' => $v['arabic_text'], 'translation' => $v['translation'], 'source' => "Al-Qur'an", 'tags' => $v['tags'], 'status' => 'approved', 'created_at' => $now, 'updated_at' => $now]);
        }
        foreach ($hadiths as $h) {
            $this->db->table('hadiths')->insert(['arabic_text' => $h['arabic_text'], 'translation' => $h['translation'], 'book' => $h['book'], 'number' => $h['number'], 'source' => $h['source'], 'status' => 'approved', 'created_at' => $now, 'updated_at' => $now]);
        }

        echo 'Seeded ' . count($quranVerses) . ' quran verses and ' . count($hadiths) . ' hadiths (semangat).' . PHP_EOL;
    }
}
