<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ContentSedihSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $quranVerses = [
            [
                'surah' => 9,
                'ayat_number' => 40,
                'arabic_text' => 'لاَ تَحْزَنْ إِنَّ اللَّهَ مَعَنَا',
                'translation' => 'Janganlah engkau berduka cita, sesungguhnya Allah bersama kita.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, pertolongan Allah, penenang hati',
            ],
            [
                'surah' => 3,
                'ayat_number' => 139,
                'arabic_text' => 'وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنْتُمُ الْأَعْلَوْنَ إِنْ كُنْتُمْ مُؤْمِنِينَ',
                'translation' => 'Janganlah kamu (merasa) lemah, dan jangan (pula) bersedih hati, padahal kamu pun orang-orang yang paling tinggi (derajatnya), jika kamu orang-orang yang beriman.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, motivasi, kesabaran',
            ],
            [
                'surah' => 12,
                'ayat_number' => 86,
                'arabic_text' => 'قَالَ إِنَّمَا أَشْكُو بَثِّي وَحُزْنِي إِلَى اللَّهِ',
                'translation' => 'Dia (Yakub) menjawab: \'Sesungguhnya hanyalah kepada Allah aku mengadukan kesusahan dan kesedihanku.\'',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, doa, mengadu kepada Allah',
            ],
            [
                'surah' => 12,
                'ayat_number' => 84,
                'arabic_text' => 'وَتَوَلَّىٰ عَنْهُمْ وَقَالَ يَا أَسَفَىٰ عَلَىٰ يُوسُفَ وَابْيَضَّتْ عَيْنَاهُ مِنَ الْحُزْنِ فَهُوَ كَظِيمٌ',
                'translation' => 'Dan dia (Yakub) berpaling dari mereka seraya berkata: \'Aduhai duka citaku terhadap Yusuf,\' dan kedua matanya menjadi putih karena kesedihan dan dia menahan amarahnya.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, kerinduan, kehilangan',
            ],
            [
                'surah' => 10,
                'ayat_number' => 62,
                'arabic_text' => 'أَلَا إِنَّ أَوْلِيَاءَ اللَّهِ لَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => 'Ingatlah, sesungguhnya wali-wali Allah itu tidak ada kekhawatiran terhadap mereka dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, ketenangan, wali Allah',
            ],
            [
                'surah' => 10,
                'ayat_number' => 65,
                'arabic_text' => 'وَلَا يَحْزُنْكَ قَوْلُهُمْ ۘ إِنَّ الْعِزَّةَ لِلَّهِ جَمِيعًا',
                'translation' => 'Dan janganlah engkau (Muhammad) sedih oleh perkataan mereka. Sesungguhnya kemuliaan itu semuanya milik Allah.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, prasangka, perlindungan',
            ],
            [
                'surah' => 16,
                'ayat_number' => 127,
                'arabic_text' => 'وَاصْبِرْ وَمَا صَبْرُكَ إِلَّا بِاللَّهِ ۚ وَلَا تَحْزَنْ عَلَيْهِمْ وَلَا تَكُ فِي ضَيْقٍ مِمَّا يَمْكُرُونَ',
                'translation' => 'Bersabarlah (hai Muhammad) dan tiadalah kesabaranmu itu melainkan dengan pertolongan Allah dan janganlah kamu bersedih hati terhadap mereka.',
                'source' => "Al-Qur'an",
                'tags' => 'sabar, sedih, tawakal',
            ],
            [
                'surah' => 28,
                'ayat_number' => 7,
                'arabic_text' => 'وَلَا تَخَافِي وَلَا تَحْزَنِي ۖ إِنَّا رَادُّوهُ إِلَيْكِ وَجَاعِلُوهُ مِنَ الْمُرْسَلِينَ',
                'translation' => '...Dan janganlah engkau takut dan janganlah (pula) bersedih hati, karena sesungguhnya Kami akan mengembalikannya kepadamu...',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, rasa takut, janji Allah',
            ],
            [
                'surah' => 28,
                'ayat_number' => 13,
                'arabic_text' => 'فَرَدَدْنَاهُ إِلَىٰ أُمِّهِ كَيْ تَقَرَّ عَيْنُهَا وَلَا تَحْزَنَ',
                'translation' => 'Maka Kami kembalikan dia (Musa) kepada ibunya, agar senang hatinya dan tidak bersedih hati...',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, kegembiraan, jawaban doa',
            ],
            [
                'surah' => 15,
                'ayat_number' => 88,
                'arabic_text' => 'وَلَا تَمُدَّنَّ عَيْنَيْكَ إِلَىٰ مَا مَتَّعْنَا بِهِ أَزْوَاجًا مِنْهُمْ وَلَا تَحْزَنْ عَلَيْهِمْ',
                'translation' => 'Jangan sekali-kali engkau menujukan pandanganmu kepada kenikmatan yang telah Kami berikan kepada beberapa golongan di antara mereka dan jangan engkau bersedih hati terhadap mereka...',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, qana\'ah, ketenangan',
            ],
            [
                'surah' => 2,
                'ayat_number' => 38,
                'arabic_text' => 'فَمَنْ تَبِعَ هُدَايَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => '...Barangsiapa mengikuti petunjuk-Ku, tidak ada kekhawatiran atas mereka, dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, petunjuk, hidayah',
            ],
            [
                'surah' => 2,
                'ayat_number' => 112,
                'arabic_text' => 'بَلَىٰ مَنْ أَسْلَمَ وَجْهَهُ لِلَّهِ وَهُوَ مُحْسِنٌ فَلَهُ أَجْرُهُ عِنْدَ رَبِّهِ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => 'Tidak! Barangsiapa menyerahkan diri kepada Allah, sedang dia berbuat baik, maka dia mendapat pahala di sisi Tuhannya dan tidak ada rasa takut pada mereka dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, keikhlasan, pahala',
            ],
            [
                'surah' => 2,
                'ayat_number' => 262,
                'arabic_text' => 'الَّذِينَ يُنْفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللَّهِ ثُمَّ لَا يُتْبِعُونَ مَا أَنْفَقُوا مَنًّا وَلَا أَذًى ۙ لَهُمْ أَجْرُهُمْ عِنْدَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => 'Orang-orang yang menginfakkan hartanya di jalan Allah, kemudian tidak mengiringi apa yang diinfakkannya itu dengan menyebut-nyebutnya dan menyakiti perasaan, mereka mendapat pahala di sisi Tuhan mereka. Tidak ada rasa takut pada mereka dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, sedekah, ketenangan',
            ],
            [
                'surah' => 2,
                'ayat_number' => 274,
                'arabic_text' => 'الَّذِينَ يُنْفِقُونَ أَمْوَالَهُمْ بِاللَّيْلِ وَالنَّهَارِ سِرًّا وَعَلَانِيَةً فَلَهُمْ أَجْرُهُمْ عِنْدَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => 'Orang-orang yang menginfakkan hartanya malam dan siang hari secara tersembunyi maupun terang-terangan, mereka mendapat pahala di sisi Tuhannya. Tidak ada rasa takut pada mereka dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, infak, ketenteraman',
            ],
            [
                'surah' => 2,
                'ayat_number' => 277,
                'arabic_text' => 'إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَأَقَامُوا الصَّلَاةَ وَآتَوُا الزَّكَاةَ لَهُمْ أَجْرُهُمْ عِنْدَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => 'Sungguh, orang-orang yang beriman, mengerjakan kebajikan, melaksanakan salat dan menunaikan zakat, mereka mendapat pahala di sisi Tuhannya. Tidak ada rasa takut pada mereka dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, iman, amal saleh',
            ],
            [
                'surah' => 5,
                'ayat_number' => 69,
                'arabic_text' => 'مَنْ آمَنَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ وَعَمِلَ صَالِحًا فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => '...Barangsiapa beriman kepada Allah, hari kemudian dan berbuat kebajikan, maka tidak ada rasa takut pada mereka dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, iman, ketenangan',
            ],
            [
                'surah' => 6,
                'ayat_number' => 33,
                'arabic_text' => 'قَدْ نَعْلَمُ إِنَّهُ لَيَحْزُنُكَ الَّذِي يَقُولُونَ ۖ فَإِنَّهُمْ لَا يُكَذِّبُونَكَ',
                'translation' => 'Sungguh, Kami mengetahui bahwa apa yang mereka katakan itu menyedihkan hatimu, (maka janganlah berduka cita) karena sebenarnya mereka bukan mendustakan engkau...',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, empati, penawar luka',
            ],
            [
                'surah' => 6,
                'ayat_number' => 48,
                'arabic_text' => 'فَمَنْ آمَنَ وَأَصْلَحَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => '...Barangsiapa beriman dan mengadakan perbaikan, maka tidak ada rasa takut pada mereka dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, perbaikan diri, ketenangan',
            ],
            [
                'surah' => 7,
                'ayat_number' => 35,
                'arabic_text' => 'فَمَنِ اتَّقَىٰ وَأَصْلَحَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
                'translation' => '...Barangsiapa bertakwa dan mengadakan perbaikan, tidak ada rasa takut pada mereka dan tidak (pula) mereka bersedih hati.',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, takwa, kedamaian',
            ],
            [
                'surah' => 41,
                'ayat_number' => 30,
                'arabic_text' => 'إِنَّ الَّذِينَ قَالُوا رَبُّنَا اللَّهُ ثُمَّ اسْتَقَامُوا تَتَنَزَّلُ عَلَيْهِمُ الْمَلَائِكَةُ أَلَّا تَخَافُوا وَلَا تَحْزَنُوا',
                'translation' => 'Sesungguhnya orang-orang yang berkata \'Tuhan kami ialah Allah\' kemudian mereka meneguhkan pendirian mereka, maka malaikat akan turun kepada mereka dengan mengatakan: \'Janganlah kamu takut dan janganlah merasa sedih...\'',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, istiqamah, kabar gembira',
            ],
            [
                'surah' => 35,
                'ayat_number' => 34,
                'arabic_text' => 'وَقَالُوا الْحَمْدُ لِلَّهِ الَّذِي أَذْهَبَ عَنَّا الْحَزَنَ ۖ إِنَّ رَبَّنَا لَغَفُورٌ شَكُورٌ',
                'translation' => 'Dan mereka berkata: \'Segala puji bagi Allah yang telah menghilangkan duka cita dari kami. Sesungguhnya Tuhan kami benar-benar Maha Pengampun lagi Maha Mensyukuri.\'',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, duka cita, surga',
            ],
            [
                'surah' => 94,
                'ayat_number' => 5,
                'arabic_text' => 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا',
                'translation' => 'Maka sesungguhnya bersama kesulitan ada kemudahan.',
                'source' => "Al-Qur'an",
                'tags' => 'kesulitan, kemudahan, optimisme',
            ],
            [
                'surah' => 94,
                'ayat_number' => 6,
                'arabic_text' => 'إِنَّ مَعَ الْعُسْرِ يُسْرًا',
                'translation' => 'Sesungguhnya bersama kesulitan ada kemudahan.',
                'source' => "Al-Qur'an",
                'tags' => 'kesulitan, kemudahan, janji Allah',
            ],
            [
                'surah' => 2,
                'ayat_number' => 153,
                'arabic_text' => 'يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
                'translation' => 'Wahai orang-orang yang beriman! Mohonlah pertolongan (kepada Allah) dengan sabar dan salat. Sungguh, Allah beserta orang-orang yang sabar.',
                'source' => "Al-Qur'an",
                'tags' => 'sabar, salat, kesusahan',
            ],
            [
                'surah' => 2,
                'ayat_number' => 155,
                'arabic_text' => 'وَلَنَبْلُوَنَّكُمْ بِشَيْءٍ مِنَ الْخَوْفِ وَالْجُوعِ وَنَقْصٍ مِنَ الْأَمْوَالِ وَالْأَنْفُسِ وَالثَّمَرَاتِ ۗ وَبَشِّرِ الصَّابِرِينَ',
                'translation' => 'Dan Kami pasti akan menguji kamu dengan sedikit ketakutan, kelaparan, kekurangan harta, jiwa, dan buah-buahan. Dan sampaikanlah kabar gembira kepada orang-orang yang sabar.',
                'source' => "Al-Qur'an",
                'tags' => 'ujian, musibah, sabar',
            ],
            [
                'surah' => 2,
                'ayat_number' => 156,
                'arabic_text' => 'الَّذِينَ إِذَا أَصَابَتْهُمْ مُصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
                'translation' => '(yaitu) orang-orang yang apabila ditimpa musibah, mereka berkata: \'Inna lillahi wa inna ilaihi raji\'un\' (Sesungguhnya kami milik Allah dan kepada-Nyalah kami kembali).',
                'source' => "Al-Qur'an",
                'tags' => 'musibah, keikhlosan, istirja',
            ],
            [
                'surah' => 2,
                'ayat_number' => 286,
                'arabic_text' => 'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
                'translation' => 'Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.',
                'source' => "Al-Qur'an",
                'tags' => 'ujian, beban, kemudahan',
            ],
            [
                'surah' => 65,
                'ayat_number' => 7,
                'arabic_text' => 'سَيَجْعَلُ اللَّهُ بَعْدَ عُسْرٍ يُسْرًا',
                'translation' => 'Allah kelak akan memberikan kelapangan setelah kesempitan.',
                'source' => "Al-Qur'an",
                'tags' => 'harapan, kesempitan, kelapangan',
            ],
            [
                'surah' => 93,
                'ayat_number' => 3,
                'arabic_text' => 'مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ',
                'translation' => 'Tuhanmu tidak meninggalkan engkau (Muhammad) dan tidak (pula) membencimu.',
                'source' => "Al-Qur'an",
                'tags' => 'penenang, kasih sayang, kesepian',
            ],
            [
                'surah' => 21,
                'ayat_number' => 87,
                'arabic_text' => 'فَنَادَىٰ فِي الظُّلُمَاتِ أَنْ لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
                'translation' => 'Maka dia berdoa dalam keadaan yang sangat gelap: \'Tidak ada tuhan selain Engkau, Mahasuci Engkau. Sungguh, aku termasuk orang-orang yang zalim.\'',
                'source' => "Al-Qur'an",
                'tags' => 'doa, kesusahan, taubat',
            ],
            [
                'surah' => 3,
                'ayat_number' => 153,
                'arabic_text' => 'لِكَيْ لَا تَحْزَنُوا عَلَىٰ مَا فَاتَكُمْ وَلَا مَا أَصَابَكُمْ',
                'translation' => '...agar kamu tidak bersedih hati terhadap apa yang luput dari kamu dan terhadap apa yang menimpa kamu...',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, takdir, ikhlas',
            ],
            [
                'surah' => 57,
                'ayat_number' => 23,
                'arabic_text' => 'لِكَيْ لَا تَأْسَوْا عَلَىٰ مَا فَاتَكُمْ وَلَا تَفْرَحُوا بِمَا آتَاكُمْ',
                'translation' => 'Agar kamu tidak bersedih hati terhadap apa yang luput dari kamu, dan jangan pula terlalu bergembira terhadap apa yang diberikan-Nya kepadamu...',
                'source' => "Al-Qur'an",
                'tags' => 'sedih, lapang dada, qada dan qadar',
            ],
            [
                'surah' => 13,
                'ayat_number' => 28,
                'arabic_text' => 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
                'translation' => 'Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.',
                'source' => "Al-Qur'an",
                'tags' => 'zikir, penenang hati, gelisah',
            ],
            [
                'surah' => 12,
                'ayat_number' => 87,
                'arabic_text' => 'وَلَا تَيْأَسُوا مِنْ رَوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِنْ رَوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ',
                'translation' => '...dan jangan kamu berputus asa dari rahmat Allah. Sesungguhnya yang berputus asa dari rahmat Allah, hanyalah kaum yang kafir.',
                'source' => "Al-Qur'an",
                'tags' => 'harapan, jangan putus asa, rahmat',
            ],
            [
                'surah' => 39,
                'ayat_number' => 53,
                'arabic_text' => 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ',
                'translation' => 'Katakanlah: \'Wahai hamba-hamba-Ku yang melampaui batas terhadap diri mereka sendiri, janganlah kamu berputus asa dari rahmat Allah...\'',
                'source' => "Al-Qur'an",
                'tags' => 'rahmat, ampunan, penghibur',
            ],
        ];

        $hadiths = [
            [
                'arabic_text' => 'مَا أَصَابَ الْمُسْلِمَ مِنْ نَصَبٍ وَلاَ وَصَبٍ وَلاَ هَمٍّ وَلاَ حَزَنٍ وَلاَ أَذًى وَلاَ غَمٍّ حَتَّى الشَّوْكَةِ يُشَاكُهَا إِلاَّ كَفَّرَ اللَّهُ بِهَا مِنْ خَطَايَاهُ',
                'translation' => 'Tidaklah seorang muslim tertimpa suatu keletihan, penyakit, kecemasan, kesedihan, gangguan, maupun duka cita—bahkan duri yang menusuknya—melainkan Allah akan menghapus dosa-dosanya dengan sebab itu.',
                'book' => 'Bukhari, Muslim',
                'number' => '5641, 2573',
                'source' => 'HR. Bukhari no. 5641 & Muslim no. 2573',
                'tags' => 'sedih, pengugur dosa, musibah',
            ],
            [
                'arabic_text' => 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ',
                'translation' => 'Ya Allah, aku berlindung kepada-Mu dari rasa gelisah, sedih, lemah, dan malas.',
                'book' => 'Bukhari',
                'number' => '6369',
                'source' => 'HR. Bukhari no. 6369',
                'tags' => 'doa, perlindungan, sedih',
            ],
            [
                'arabic_text' => 'عَجَبًا لأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ وَلَيْسَ ذَاكَ لأَحَدٍ إِلاَّ لِلْمُؤْمِنِ إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْرًا لَهُ وَإِنْ أَصَابَتْهُ ضَرَّاءُ صَبَرَ فَكَانَ خَيْرًا لَهُ',
                'translation' => 'Sungguh menakjubkan urusan seorang mukmin, seluruh urusannya adalah baik baginya. Jika ia mendapatkan kesenangan ia bersyukur, maka itu baik baginya. Dan jika ditimpa kesusahan ia bersabar, maka itu baik baginya.',
                'book' => 'Muslim',
                'number' => '2999',
                'source' => 'HR. Muslim no. 2999',
                'tags' => 'sabar, syukur, mukmin',
            ],
            [
                'arabic_text' => 'مَا أَصَابَ أَحَدًا قَطُّ هَمٌّ وَلاَ حَزَنٌ فَقَالَ اللَّهُمَّ إِنِّي عَبْدُكَ وَابْنُ عَبْدِكَ... إِلاَّ أَذْهَبَ اللَّهُ هَمَّهُ وَحُزْنَهُ وَأَبْدَلَهُ مَكَانَهُ فَرَجًا',
                'translation' => 'Tidaklah seseorang tertimpa duka cita dan kesedihan lalu membaca doa \'Ya Allah, sesungguhnya aku adalah hamba-Mu...\' melainkan Allah akan menghilangkan duka citanya dan menggantikannya dengan kelapangan.',
                'book' => 'Ahmad, Ibnu Hibban',
                'number' => '3712',
                'source' => 'HR. Ahmad no. 3712 & Ibn Hibban',
                'tags' => 'doa penawar sedih, kelapangan',
            ],
            [
                'arabic_text' => 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ وَأَصْلِحْ لِي شَأْنِي كُلَّهُ لَا إِلَهَ إِلَّا أَنْتَ',
                'translation' => 'Ya Allah, rahmat-Mu yang aku harapkan, maka janganlah Engkau serahkan aku kepada diriku sendiri walau sekejap mata pun, dan perbaikilah seluruh urusanku. Tiada tuhan selain Engkau.',
                'book' => 'Abu Dawud',
                'number' => '5090',
                'source' => 'HR. Abu Dawud no. 5090',
                'tags' => 'doa kesusahan, pertolongan',
            ],
            [
                'arabic_text' => 'إِنَّمَا الصَّبْرُ عِنْدَ الصَّدْمَةِ الأُولَى',
                'translation' => 'Sesungguhnya kesabaran (yang sebenarnya) adalah pada saat pertama kali tertimpa musibah.',
                'book' => 'Bukhari, Muslim',
                'number' => '1283, 926',
                'source' => 'HR. Bukhari no. 1283 & Muslim no. 926',
                'tags' => 'sabar, musibah, keteguhan',
            ],
            [
                'arabic_text' => 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُصِبْ مِنْهُ',
                'translation' => 'Barangsiapa yang dikehendaki kebaikan oleh Allah, maka Dia akan memberinya ujian/musibah.',
                'book' => 'Bukhari',
                'number' => '5645',
                'source' => 'HR. Bukhari no. 5645',
                'tags' => 'ujian, kebaikan, hikmah',
            ],
            [
                'arabic_text' => 'إِنَّ عِظَمَ الْجَزَاءِ مَعَ عِظَمِ الْبَلاَءِ وَإِنَّ اللَّهَ إِذَا أَحَبَّ قَوْمًا ابْتَلاَهُمْ',
                'translation' => 'Sesungguhnya besarnya balasan disertai besarnya ujian. Dan sesungguhnya apabila Allah mencintai suatu kaum, Dia akan menguji mereka.',
                'book' => 'Tirmidzi',
                'number' => '2396',
                'source' => 'HR. Tirmidzi no. 2396',
                'tags' => 'cinta Allah, ujian, pahala',
            ],
            [
                'arabic_text' => 'اللهُ اللهُ رَبِّي لَا أُشْرِكُ بِهِ شَيْئًا',
                'translation' => 'Allah, Allah adalah Tuhanku, aku tidak mempersekutukan-Nya dengan sesuatu apa pun. (Dibaca saat mengalami kesusahan/kesedihan mendalam).',
                'book' => 'Abu Dawud',
                'number' => '1525',
                'source' => 'HR. Abu Dawud no. 1525',
                'tags' => 'doa kesusahan, tauhid',
            ],
            [
                'arabic_text' => 'إِنَّ العَيْنَ تَدْمَعُ، وَالقَلْبَ يَحْزَنُ، وَلاَ نَقُولُ إِلَّا مَا يَرْضَى رَبُّنَا',
                'translation' => 'Mata boleh menangis dan hati boleh bersedih, namun kami tidak mengucapkan kecuali apa yang diridhai oleh Rabb kami.',
                'book' => 'Bukhari',
                'number' => '1303',
                'source' => 'HR. Bukhari no. 1303',
                'tags' => 'tangisan, kesedihan, ridha',
            ],
            [
                'arabic_text' => 'وَاعْلَمْ أَنَّ النَّصْرَ مَعَ الصَّبْرِ وَأَنَّ الْفَرَجَ مَعَ الْكَرْبِ وَأَنَّ مَعَ الْعُسْرِ يُسْرًا',
                'translation' => 'Ketahuilah bahwa pertolongan itu bersama kesabaran, kelapangan itu bersama kesusahan, dan kemudahan itu bersama kesulitan.',
                'book' => 'Ahmad',
                'number' => '2803',
                'source' => 'HR. Ahmad no. 2803',
                'tags' => 'sabar, kemudahan, pertolongan',
            ],
            [
                'arabic_text' => 'دَعْوَةُ ذِي النُّونِ إِذْ دَعَا وَهُوَ فِي بَطْنِ الحُوتِ... لَمْ يَدْعُ بِهَا رَجُلٌ مُسْلِمٌ فِي شَيْءٍ قَطُّ إِلاَّ اسْتَجَابَ اللَّهُ لَهُ',
                'translation' => 'Doa Dzun Nuun (Nabi Yunus) ketika berdoa di dalam perut ikan... Tidaklah seorang muslim berdoa dengannya dalam suatu masalah melainkan Allah akan mengabulkan doanya.',
                'book' => 'Tirmidzi',
                'number' => '3505',
                'source' => 'HR. Tirmidzi no. 3505',
                'tags' => 'doa kesusahan, Nabi Yunus, pengabulan doa',
            ],
            [
                'arabic_text' => 'لاَ إِلهَ إِلاَّ اللهُ الْعَظِيْمُ الْحَلِيْمُ، لاَ إِلهَ إِلاَّ اللهُ رَبُّ الْعَرْشِ الْعَظِيْمِ',
                'translation' => 'Tiada tuhan selain Allah Yang Maha Agung lagi Maha Penyantun. Tiada tuhan selain Allah, Rabb \'Arsy yang agung. (Doa ketika ditimpa kesusahan berat).',
                'book' => 'Bukhari, Muslim',
                'number' => '6345, 2730',
                'source' => 'HR. Bukhari no. 6345 & Muslim no. 2730',
                'tags' => 'doa kesusahan, kalimat thayyibah',
            ],
            [
                'arabic_text' => 'الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ',
                'translation' => 'Dunia adalah penjara bagi orang mukmin dan surga bagi orang kafir.',
                'book' => 'Muslim',
                'number' => '2956',
                'source' => 'HR. Muslim no. 2956',
                'tags' => 'dunia, kesabaran, mukmin',
            ],
            [
                'arabic_text' => 'مَا يَزَالُ الْبَلاَءُ بِالْمُؤْمِنِ وَالْمُؤْمِنَةِ فِي نَفْسِهِ وَوَلَدِهِ وَمَالِهِ حَتَّى يَلْقَى اللَّهَ وَمَا عَلَيْهِ خَطِيئَةٌ',
                'translation' => 'Ujian akan senantiasa menimpa seorang mukmin dan mukminah, pada dirinya, anaknya, dan hartanya, hingga ia berjumpa dengan Allah tanpa membawa dosa sedikit pun.',
                'book' => 'Tirmidzi',
                'number' => '2399',
                'source' => 'HR. Tirmidzi no. 2399',
                'tags' => 'ujian, pengampunan dosa, kesabaran',
            ],
        ];

        foreach ($quranVerses as $verse) {
            $this->db->table('quran_verses')->insert([
                'surah'       => $verse['surah'],
                'ayat_number' => $verse['ayat_number'],
                'arabic_text' => $verse['arabic_text'],
                'translation' => $verse['translation'],
                'source'      => $verse['source'],
                'tags'        => $verse['tags'],
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ]);
        }

        foreach ($hadiths as $hadith) {
            $this->db->table('hadiths')->insert([
                'arabic_text' => $hadith['arabic_text'],
                'translation' => $hadith['translation'],
                'book'        => $hadith['book'],
                'number'      => $hadith['number'],
                'source'      => $hadith['source'],
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ]);
        }

        echo 'Seeded ' . count($quranVerses) . ' quran verses and ' . count($hadiths) . ' hadiths.' . PHP_EOL;
    }
}
